[13.0][IMP] product_abc_classification: several improvements
OCA/product-attribute pull request #1010
Opened 2022-02-02 17:15 UTC by MiquelRForgeFlow

Several improvements here:

- No need to have unique percentages
- Move profiles to templates
- And more improvements.

cc: @emagdalenaC2i, @legalsylvain, @albariera

2022-02-02 19:24 UTC, legalsylvain commented
Sorry i still don't use this module, so don't have the knowlegde to review. But thanks for the improvment !

2022-02-03 08:45 UTC, rousseldenis requested changes
Code review.

This should be updated to major.

2022-02-03 08:45 UTC, rousseldenis commented on product_abc_classification/models/abc_classification_profile.py
> +        action = self.env.ref("product.product_template_action").read()[0]
```suggestion
        action = self.env["ir.actions.act_window"]._for_xml_id("product.product_template_action")
```

2022-02-03 09:05 UTC, rousseldenis approved these changes

2022-02-03 10:21 UTC, albariera requested changes
I don't really understand why we are moving the profiles to the template. I suppose that the functionality was intended to be the same but to simplify the code. However, wouldn't it make sense that each product variant could have a different classification? Maybe one product variant is more sold than another and needs more inventory control. Just asking, you'll have more knowledge about it. 
But anyway if you want to move it to the template, at the moment it is not working fine:
- The profile is not being assigned to the product.template, the method _fill_data_from_stock_moves should be modified to product.template
- If you try to group from the product.product view by the level or profile you get this error: Fields in 'groupby' must be database-persisted fields (no computed fields)
- Why do we make invisible at product.template the level and not the profile? We should make invisible both or any, shouldn't we?

2022-02-03 10:21 UTC, albariera commented on product_abc_classification/models/abc_classification_profile.py
> +        action = self.env["ir.actions.act_window"].for_xml_id(
When clicking the button it gives me this error:
TypeError: for_xml_id() missing 1 required positional argument: 'xml_id'
 
The method has to be _for_xml_id("product.product_template_action"), with the underscore or for_xml_id("product", "product_template_action") without the underscore

2022-02-03 10:36 UTC, MiquelRForgeFlow commented
> I don't really understand why we are moving the profiles to the template.

That was a suggestion of @legalsylvain done in https://github.com/OCA/product-attribute/pull/623#discussion_r608669761.

> However, wouldn't it make sense that each product variant could have a different classification? Maybe one product variant is more sold than another and needs more inventory control. Just asking, you'll have more knowledge about it.

Well, that's something about I am not sure, something that @legalsylvain asked about. I think I will delete that commit for now, to let the other commits get merged. If in the future any of you want to put profile in the template, then another PR can be done.

2022-02-03 11:05 UTC, MiquelRForgeFlow commented on product_abc_classification/models/abc_classification_profile.py
> +        action = self.env["ir.actions.act_window"].for_xml_id(
yeah, the confusion comes because `for_xml_id` of v13 and `_for_xml_id` of v14 are different. Thanks for testing.

2022-02-03 12:08 UTC, albariera commented
Ok! We can merge these improvements and talk about the variant/template in other PR.
Also, the smart button is not working as expected
![test_smart_button](https://user-images.githubusercontent.com/79082305/152339997-af742cf3-b062-4874-8f13-d4b234f3df46.gif)
:

2022-02-03 12:42 UTC, albariera approved these changes
LGTM :+1:

2022-02-04 11:04 UTC, MiquelRForgeFlow commented
/ocabot merge major

2022-02-04 11:45 UTC, merged