14.0 mig product custom info
OCA/product-attribute pull request #1054
Opened 2022-04-12 08:07 UTC by ilyasProgrammer

2022-04-12 10:16 UTC, francesco-ooops approved these changes
LGTM

2022-04-12 15:48 UTC, elvise approved these changes
LGTM

2022-04-19 07:46 UTC, francesco-ooops commented
@OCA/product-maintainers merge?

2022-04-19 07:51 UTC, rousseldenis commented
/ocabot migration product_custom_info

2022-04-19 07:55 UTC, rousseldenis requested changes
@ilyasProgrammer Thanks for this. Please add missing readme fragments

2022-04-19 07:55 UTC, rousseldenis commented on product_custom_info/README.rst
> -* You depend from module ``base_custom_info``, found in `OCA/server-tools
@ilyasProgrammer If you remove the README you need to fill in all the corresponding readme fragments (INSTALL/CONFIGURE/CONTRIBUTORS...).

2022-04-20 13:24 UTC, francesco-ooops commented
@rousseldenis good now? :)

2022-04-20 13:43 UTC, rousseldenis commented
> @rousseldenis good now? :)

Nope.

Please move each README section to corresponding section in readme/*.rst

See https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2022-04-21 07:52 UTC, rousseldenis commented
@ilyasProgrammer Ok, better now. Could you squash additional commit in the migration one ?

2022-04-22 11:04 UTC, francesco-ooops commented
@rousseldenis code ok for merge?

2022-04-28 07:36 UTC, francesco-ooops commented
@OCA/product-maintainers can this one be reviewed/merged? thanks!

2022-05-04 08:21 UTC, francesco-ooops commented
@rousseldenis @JordiBForgeFlow sorry to tag you directly, can you take a look when you have some time?

2022-05-13 09:56 UTC, francesco-ooops commented
@OCA/product-maintainers :)
![image](https://user-images.githubusercontent.com/55489873/168259603-3eaad3d3-5bf8-4c74-b21a-3ed93a6fd68d.png)

2022-05-16 18:06 UTC, rousseldenis approved these changes

2022-05-16 18:54 UTC, rousseldenis commented
/ocabot merge patch

2022-05-16 19:43 UTC, merged