[ADD] product_template_tags_group
OCA/product-attribute pull request #1087
Opened 2022-06-08 08:54 UTC by SirTakobi

Allow to create a group for tags defined by https://github.com/OCA/product-attribute/tree/6e590f70a06dc6ddbd1bae7ce4fe430812c7d7b8/product_template_tags

2022-06-08 10:06 UTC, eLBati requested changes

2022-06-08 10:06 UTC, eLBati commented on product_template_tags_group/security/product_template_tag_group_rule.xml
> +</odoo>
I think a multi company rule is not need, as the main data are products, which have multi company rules.
I would follow the same approach as `product.category` about this

2022-06-09 14:31 UTC, eLBati commented on product_template_tags_group/security/product_template_tag_group_rule.xml
> +</odoo>
Nevermind, didn't see https://github.com/OCA/product-attribute/blob/3e94baf1757a5e9d783adf366f4a210660f661dc/product_template_tags/security/product_template_rule.xml

2022-06-20 08:47 UTC, eLBati approved these changes
Thanks

2022-06-29 14:46 UTC, carmenbianca requested changes
Mostly LGTM, one comment.

2022-06-29 14:46 UTC, carmenbianca commented on product_template_tags_group/security/ir.model.access.csv
> +manage_product_template_tag_group,manage_product_template_tag_group,model_product_template_tag_group,base.group_user,1,1,1,1
Comparing this against the permissions in `product`, the permissions should be `1,0,0,0` for `base.group_user` and `1,1,1,1` for `base.group_system`.

2022-06-30 09:35 UTC, SirTakobi commented on product_template_tags_group/security/ir.model.access.csv
> +manage_product_template_tag_group,manage_product_template_tag_group,model_product_template_tag_group,base.group_user,1,1,1,1
Thanks for the review!
Note that tags groups are not linked to products but only to tags, so these permissions have to be aligned with permissions defined on tags, and right now they are:
> ```
> <odoo>
>     <record id="product_template_tag_access_user" model="ir.model.access">
>         <field name="name">product.template.tag access user (in product_template_tags)</field>
>         <field name="model_id" ref="model_product_template_tag"/>
>         <field name="group_id" ref="base.group_user"/>
>         <field name="perm_read" eval="1"/>
>         <field name="perm_create" eval="1"/>
>         <field name="perm_write" eval="1"/>
>         <field name="perm_unlink" eval="1"/>
>     </record>
> </odoo>
> ```
(ref. https://github.com/OCA/product-attribute/blob/486f3e850158f88e8630a2fba5acda465967fa84/product_template_tags/security/product_template_tag.xml)

Then product tags are used in products (and that might be why you looked at product's permissions), but it looks like who defined product tags chose to use different permissions from products' permissions, here I am sticking with that choice.

2022-06-30 09:37 UTC, carmenbianca commented on product_template_tags_group/security/ir.model.access.csv
> +manage_product_template_tag_group,manage_product_template_tag_group,model_product_template_tag_group,base.group_user,1,1,1,1
Fair! Resolved.

2022-06-30 09:37 UTC, carmenbianca approved these changes

2022-07-13 07:47 UTC, SirTakobi commented
@OCA/product-maintainers can this be merged? Thanks!

2022-08-22 15:17 UTC, SirTakobi commented
@OCA/product-maintainers can this be merged? Thanks!

2022-08-30 15:57 UTC, eLBati approved these changes

2023-01-02 10:01 UTC, SirTakobi commented
@OCA/product-maintainers can this be merged? It already has enough reviews, thanks!

2023-05-16 09:40 UTC, SirTakobi commented
@OCA/product-maintainers can this be merged? It already has enough reviews, thanks!

2023-10-29 12:13 UTC, closed without merging