[IMP] product_state (Move Data to Demo)
OCA/product-attribute pull request #1088
Opened 2022-06-08 19:36 UTC by patrickrwilson

The stages in the data file is demo data. Having it in data causes issues when the module is updated and the sample stages were deleted as it will repopulate them, even though there is the no update flag.

It was already stated in the roadmap readme for v15, but why not fix it here.

2022-06-08 22:01 UTC, legalsylvain reviewed
Hi.
question : don't you have to add a pre-migration script to drop the xml_id for people upgrading production database in V14 ?
not sure. Just a question.

2022-06-15 08:39 UTC, rousseldenis commented
@Cedric-Pigeon @simahawk What do you think of this ? I'm not sure about it

2022-06-15 09:02 UTC, Cedric-Pigeon requested changes
I am not against this proposal but for sure a migration script is required to avoid any breaks on existing installation

2022-06-15 09:05 UTC, rousseldenis commented
> I am not against this proposal but for sure a migration script is required to avoid any breaks on existing installation

The problem I see with that is if you install the module on existing installation, existing products will have no state unless you provide too an init_hook... but with which state ?

2022-06-15 12:59 UTC, patrickrwilson commented
For existing installations, I don't think we want to drop any existing states because if its currently using any states at all, whether they were installed by this module before the change or not, we wouldn't want to drop the xml's that were previously installed as that can cause issues and impede business workflows already in place.

Also, having no states seems fine, and doesn't cause issues when no states are in the system. Products function just fine without  them.

2022-11-16 07:59 UTC, simahawk commented
I missed the ping here...  Arriving late to the party :smile: 

> > I am not against this proposal but for sure a migration script is required to avoid any breaks on existing installation
> 
> The problem I see with that is if you install the module on existing installation, existing products will have no state unless you provide too an init_hook... but with which state ?

For new installations that's not a problem IMO, but it should be documented.

My top concern is to not hinder existing installations.
IMO we should:
1. drop existing XIDs to unlink existing records from the module (should be harmless I think)
2. rename demo records' XIDS w/ `demo_*` prefix

2023-04-23 12:13 UTC, closed without merging