[15.0][MIG] product_restricted_type: Migration to 15.0
OCA/product-attribute pull request #1140
Opened 2022-09-05 07:41 UTC by AnnaPForgeFlow

Standard migration to 15.0

2022-09-12 14:50 UTC, JuanyDForgeflow approved these changes
LGTM!!

2022-09-19 10:59 UTC, GuillemCForgeFlow approved these changes
LGTM! :+1:

2022-09-20 09:15 UTC, AaronHForgeFlow approved these changes
Functional review

2022-09-20 09:18 UTC, HviorForgeFlow requested changes

2022-09-20 09:18 UTC, HviorForgeFlow commented on product_restricted_type/models/product.py
> +        string="Restricted Product Type ",
I think pre-commit is failing due to string has the same name as the transformed `restricted_product_type` to String. Please remove the string entry

2022-09-20 11:35 UTC, JordiBForgeFlow commented
/ocabot migration product_restricted_type
/ocabot merge nobump

2022-09-20 11:42 UTC, merged