[14.0][ADD] product_supplierinfo_stock_picking_type: New addon.
OCA/product-attribute pull request #1142
Opened 2022-09-12 06:51 UTC by victoralmau

New addon.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT38584

2022-09-12 10:26 UTC, pedrobaeza commented
@LudLaf please review README

2022-09-12 10:28 UTC, pedrobaeza requested changes

2022-09-12 10:28 UTC, pedrobaeza commented on product_supplierinfo_stock_picking_type/models/product_product.py
> +                lambda x: x.picking_type_id == params.get("order_id").picking_type_id
```suggestion
                lambda x: not x.picking_type_id or x.picking_type_id == params.get("order_id").picking_type_id
```

2022-09-12 10:28 UTC, pedrobaeza commented on product_supplierinfo_stock_picking_type/models/product_product.py
> +                lambda x: x.picking_type_id == params.get("order_id").picking_type_id
Include a test case for this False one as well.

2022-09-12 11:01 UTC, pedrobaeza approved these changes
Code review. README not reviewed

2022-09-12 17:08 UTC, LudLaf requested changes

2022-09-12 17:08 UTC, LudLaf commented on product_supplierinfo_stock_picking_type/readme/USAGE.rst
> +#. The unit price of the product will be 10.
```suggestion
#. Go to *Inventory > Configuration > Operations types* and create two records
   named 'Incoming A' and 'Incoming B' with 'Type of Operation' equal to
   'Receipt'.
#. Go to *Inventory > Products > Products*, then create a product named
   'Test product' and set 'Purchase' tab as follows:
#. [Vendor line 1] Vendor: Azure Interior, Picking type: Incoming A, Price: 5.
#. [Vendor line 2] Vendor: Azure Interior, Picking type: Incoming B, Price: 10.
#. Then click on 'Save'.

Next steps:

Purchase order flow A:
#. Go to *Purchase > Orders > Requests for Quotation* and create a new order
   as follows:
#. Vendor: Azure Interior; Product: Test product; Deliver To: Incoming A
   (under 'Other information' tab)
#. The unit price of the product will be 5.

Purchase order flow B:
#. Go to *Purchase > Orders > Requests for Quotation* and create a new order
   as follows:
#. Vendor: Azure Interior; Product: Test product; Deliver To: Incoming B
   (under 'Other information' tab)
#. The unit price of the product will be 10.
```

2022-09-12 17:08 UTC, LudLaf commented on product_supplierinfo_stock_picking_type/readme/USAGE.rst
> +#. The unit price of the product will be 10.
Replacing this whole text will probably be easier.

2022-09-13 06:19 UTC, victoralmau commented
Changes done.

2022-09-13 08:22 UTC, LudLaf approved these changes

2022-09-13 08:53 UTC, chienandalu approved these changes
Tested :+1: (I had to remove all the purchase modules to avoid behavior interferences...)

Naif question: should the prices be updated when we change the picking typein the purchase order?

2022-09-13 13:52 UTC, victoralmau commented
> Tested +1 (I had to remove all the purchase modules to avoid behavior interferences...)
> 
> Naif question: should the prices be updated when we change the picking typein the purchase order?

Interesting, good details.

I have added `picking_type_id` field to the form view of `product.supplierinfo`.

I have added the `onchange()` in the purchase order to update the line prices when the `picking_type_id` field is changed.

2022-09-13 14:01 UTC, pedrobaeza commented
/ocabot merge nobump

2022-09-13 14:14 UTC, merged