[15.0][MIG] product_lot_sequence
OCA/product-attribute pull request #1145
Opened 2022-09-15 11:17 UTC by i-vyshnevska

plus include
https://github.com/OCA/product-attribute/pull/1111

2022-11-07 10:21 UTC, grindtildeath commented
@i-vyshnevska Can you please check https://github.com/camptocamp/product-attribute/pull/2 ?

2022-11-07 13:15 UTC, grindtildeath approved these changes

2022-11-07 13:22 UTC, simahawk commented
@i-vyshnevska pls remove the merge commit

2022-11-07 13:23 UTC, sebalix approved these changes

2022-11-07 13:24 UTC, simahawk requested changes
history to fix

2022-11-07 13:24 UTC, simahawk commented on product_lot_sequence/readme/CONTRIBUTORS.rst
> +* Domantas Girdžiūnas <domantas@vialaurea.lt>
you can add yourselves here

2022-11-07 13:25 UTC, simahawk commented
/ocabot migration product_lot_sequence

2022-11-07 16:57 UTC, gurneyalex approved these changes

2022-12-21 13:16 UTC, simahawk commented
/ocabot merge nobump

2022-12-21 13:23 UTC, merged