[ADD][16.0] product_print_category
OCA/product-attribute pull request #1176
Opened 2022-10-24 19:19 UTC by legalsylvain

2022-10-26 14:37 UTC, remytms commented
@legalsylvain I seams to work on my local computer with a fresh 16.0 installed with demo-data.

This is the patch I applied before testing:
```
diff --git a/product_print_category/report/report_pricetag.xml b/product_print_category/report/report_pricetag.xml
index 1be2a8a..37b01f8 100644
--- a/product_print_category/report/report_pricetag.xml
+++ b/product_print_category/report/report_pricetag.xml
@@ -11,7 +11,7 @@ License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
             <t t-foreach="categories_data" t-as="category_data">
                 <div class="page">
                     <t
-                        t-call="#{ category_data['print_category'].qweb_view_id.xml_id }"
+                        t-call="#{ category_data['print_category'].qweb_view_id.key }"
                     />
                 </div>
             </t>
```

This is the PDF report I get: 
[Pricetags.pdf](https://github.com/OCA/product-attribute/files/9870510/Pricetags.pdf)

2022-10-26 14:39 UTC, remytms commented
@legalsylvain Tell me which error you get when using my patch, if you encounter some. Or a way to reproduce it. :)

2022-10-26 14:43 UTC, legalsylvain commented
> @legalsylvain Tell me which error you get when using my patch, if you encounter some. Or a way to reproduce it. :)

That's weird ! I tested again, and all seems to work properly. I added the last commit to backport your improvment.

Thanks ! 

Note : could you review the rest of the PR ?

2022-10-26 14:44 UTC, remytms commented
For sure I can do a review. :)

2022-10-26 15:20 UTC, remytms requested changes
Read all the code and tested it with demo data. Just some naming changes requested.

2022-10-26 15:20 UTC, remytms commented on product_print_category/README.rst
> +This module is part of the `grap/grap-odoo-incubator <https://github.com/grap/grap-odoo-incubator/tree/12.0/product_print_category>`_ project on GitHub.
I think that theses links to https://github.com/grap/grap-odoo-incubator should be replaced by the OCA one, has this module will be in OCA now. :)

2022-10-26 15:20 UTC, remytms commented on product_print_category/__manifest__.py
> +    "Coop IT Easy SCRLfs, "
Can you change this to `Coop IT Easy SC` (juridic name reform has occurred in Belgium).

2022-12-09 10:50 UTC, legalsylvain commented on product_print_category/README.rst
> +This module is part of the `grap/grap-odoo-incubator <https://github.com/grap/grap-odoo-incubator/tree/12.0/product_print_category>`_ project on GitHub.
No need. This text is autogenerated by bot when merging. Only fragment should be reviewed.

2022-12-09 10:54 UTC, legalsylvain commented on product_print_category/__manifest__.py
> +    "Coop IT Easy SCRLfs, "
done.

2022-12-15 09:26 UTC, remytms commented on product_print_category/README.rst
> +This module is part of the `grap/grap-odoo-incubator <https://github.com/grap/grap-odoo-incubator/tree/12.0/product_print_category>`_ project on GitHub.
Thanks for the info. :)

2022-12-15 09:26 UTC, remytms approved these changes

2022-12-15 09:56 UTC, legalsylvain commented
@PierrickBrun could you review this one ?

2022-12-16 15:33 UTC, PierrickBrun reviewed
The product.template view is broken

![Capture d’écran du 2022-12-16 16-31-35](https://user-images.githubusercontent.com/8819682/208133081-2b81a64a-28e4-4ef9-9c21-2a7b330023eb.png)

Apart from that everything looks functional

2022-12-17 21:18 UTC, legalsylvain commented
@PierrickBrun : I fixed the view issue. could you take a look, and update your review ? 
thanks !

2022-12-26 16:49 UTC, PierrickBrun approved these changes

2023-01-18 12:50 UTC, legalsylvain commented
Please avoid to merge, I have a final change to do before.

2023-02-15 12:39 UTC, rousseldenis commented
@legalsylvain Still WIP ?

2023-03-21 15:26 UTC, legalsylvain commented
Hi @rousseldenis That's OK for me !

2023-04-20 09:54 UTC, remytms commented
@legalsylvain Ping me if you need another review since your last changes. And if I understand correctly, this is not WIP anymore, so you can remove this from the title of this PR. :)

2023-04-20 16:09 UTC, legalsylvain commented
@rousseldenis could you merge it ?

2023-05-03 09:28 UTC, rousseldenis commented
@legalsylvain Could you just remove the merge commit ? Thanks

2023-05-03 09:49 UTC, legalsylvain commented
> @legalsylvain Could you just remove the merge commit ? Thanks

done.

2023-06-22 12:30 UTC, legalsylvain commented
Hi maintainers : could you merge it ?

2023-07-12 12:38 UTC, carmenbianca commented
Kind ping @ maintainers to have a look at merging this :)

2023-07-31 10:30 UTC, legalsylvain commented
/ocabot merge patch

2023-07-31 10:31 UTC, legalsylvain commented
@OCA/product-maintainers : this one can be merged.

2023-10-30 10:05 UTC, carmenbianca commented
@OCA/product-maintainers this is still ready to be merged :tada:

2023-11-06 16:25 UTC, bguillot commented
/ocabot merge patch

2023-11-06 20:37 UTC, dreispt commented
/ocabot merge nobump

2023-11-06 21:12 UTC, legalsylvain commented
It should be OK now. could you retry to merge ?

2023-11-06 21:27 UTC, dreispt commented
Sure! Shouldn't you be partying?!

/ocabot merge nobump

2023-11-06 21:35 UTC, merged