[16.0] stock production lot expired dates
OCA/product-attribute pull request #1217
Opened 2022-11-29 21:08 UTC by glitchov

Migration from 10.0 and integration into OCA

2022-11-30 10:45 UTC, glitchov commented
Bad module name

2022-11-30 13:42 UTC, rousseldenis commented
@glitchov It's an addition, not a migration

2022-12-05 14:03 UTC, lmignon requested changes
@glitchov  Can you add "ACSONE SA/NV" into the author's list and add copyright for acsone PLZ

2022-12-05 14:39 UTC, lmignon commented on stock_production_lot_expired_date/tests/test_stock_production_lot_expired_date.py
> +    post_install = True
@glitchov Les tests ne doivent pas tourner en post_install.. Tu peux supprimer ces deux lignes

2022-12-05 16:22 UTC, lmignon approved these changes

2023-01-19 14:35 UTC, FrancoMaxime requested changes
as you're adding a new module, can you regroup all your commits into one, with a name like "[ADD] stock_production_lot_expired_date"

2023-01-19 16:02 UTC, FrancoMaxime approved these changes
LGTM, thanks for the correction

2023-01-19 16:10 UTC, baimont commented on stock_production_lot_expired_date/readme/DESCRIPTION.rst
> +This module allow to facilitate the input of stock production lot expired dates:
```suggestion
This module allows to facilitate the input of stock production lot expired dates:
```

2023-01-19 16:14 UTC, baimont commented on stock_production_lot_expired_date/views/res_config_settings.xml
> +        >stock.config.settings.form (in stock_production_lot_expiry)</field>
```suggestion
        >stock.config.settings.form (in stock_production_lot_expired_date)</field>
```

2023-01-19 16:29 UTC, baimont commented on stock_production_lot_expired_date/tests/test_stock_production_lot_expired_date.py
> +                # Check the onchange not fails with no value
```suggestion
                # Check the onchange does not fail with no value
```

2023-01-19 16:30 UTC, baimont commented on stock_production_lot_expired_date/views/res_config_settings.xml
> +        >stock.config.settings.form (in stock_production_lot_expiry)</field>
```suggestion
        >stock.config.settings.form (in stock_production_lot_expired_date)</field>
```

2023-01-19 16:30 UTC, baimont approved these changes

2023-01-23 16:36 UTC, lmignon commented
@glitchov Can you take into account the last comments from @baimont ? Thanks in advance!

2023-01-24 08:31 UTC, glitchov commented
@baimont Can you check please ?

2023-02-09 07:52 UTC, rousseldenis approved these changes
Code review

2023-02-09 07:52 UTC, rousseldenis commented
/ocabot merge patch

2023-02-10 14:45 UTC, rousseldenis commented
/ocabot merge patch

2023-02-10 14:50 UTC, merged