[MIG][16.0] product total weight from packaging
OCA/product-attribute pull request #1221
Opened 2022-11-30 14:41 UTC by glitchov

Migration from 14.0

2022-12-05 14:11 UTC, lmignon approved these changes
Code review

2023-01-19 15:29 UTC, FrancoMaxime approved these changes
code review

2023-01-19 15:35 UTC, xavier-bouquiaux approved these changes
LGTM technical side

2023-03-30 11:10 UTC, jbaudoux requested changes
The max_weight is a concept that was introduced in odoo delivery module to define the transporter weight limit for the shipped packaging. Before v16, the transporter packaging and product packaging was the same model `product.packaging`. Now the transporter packaging is moved to the model `stock.package.type`.
In v13, max_weight defined in delivery module on `product.packaging` was used also for product packaging dimension.
In v14, the weight field was added on the `product.packaging` and the max_weight was still coming from delivery module. This was introducing inconsistency as some modules migrated from v13 to v14 still rely on max_weight and some rely on the new weight field.
In v16, we have to drop this max_weight on product.packaging as the delivery module moved it to stock.package.type and rely only on the weight.
The migration of the product_packaging_dimension https://github.com/OCA/product-attribute/pull/1161 has to be fixed to not expose the old max_weight field and any data on max_weight must be moved to weight if empty.

This module also deserves a big warning that it is lacking the weight uom conversions as it depends on product_packaging_dimension that depends on product_logistics_uom that allows to set a uom on the weight. The sum in this module is assuming all weights are in kg

2023-03-30 11:10 UTC, jbaudoux commented on product_total_weight_from_packaging/models/product.py
> +                "_packaging_filter": lambda p: p.max_weight,
```suggestion
                "_packaging_filter": lambda p: p.weight,
```

2023-03-30 11:10 UTC, jbaudoux commented on product_total_weight_from_packaging/models/product.py
> +            res["weight"] = packaging.max_weight
```suggestion
            res["weight"] = packaging.weight
```

2023-07-12 12:30 UTC, victorvermot commented
Hello @glitchov, @lmignon I have added a small pr the situation raised by @jbaudoux
- https://github.com/acsone/product-attribute/pull/6

2023-07-12 12:41 UTC, leemannd commented
Hello @glitchov , there are conflicts with the branch 16.0, by any chance could you have a look at it and maybe perform a rebase?

2023-07-12 13:06 UTC, lmignon commented
@leemannd @victorvermot This branch is now rebased and comments from @jbaudoux are included

2023-07-12 13:33 UTC, jbaudoux approved these changes
Thanks @lmignon for the update.

Not related to the migration but this module still deserves a big warning that it is lacking the weight uom conversions as it depends on product_packaging_dimension that depends on product_logistics_uom that allows to set a uom on the weight. The sum in this module is assuming all weights are in kg

2023-07-12 13:54 UTC, lmignon commented
@jbaudoux Warning added...
![image](https://github.com/OCA/product-attribute/assets/544090/4c1397b6-0ed7-485e-9904-dd0251af2f98)

2023-07-12 14:19 UTC, leemannd approved these changes

2023-12-22 10:20 UTC, dreispt commented
/ocabot merge nobump

2023-12-22 10:29 UTC, merged