[14.0][IMP] product_pricelist_direct_print: allow export product images
OCA/product-attribute pull request #1231
Opened 2022-12-15 14:23 UTC by ferran-S73

Allow exporting the pricelist report with product images. For scaling I set the images dimensions to be 64px at max.

Here's an example of the resulting report:

![imagen](https://user-images.githubusercontent.com/79899255/207885279-4f4ac09d-9b33-4973-b72b-d2d3f2f019c1.png)

2022-12-16 12:37 UTC, legalsylvain requested changes
Hi. Thanks for this improvment. 
Could you apply changes on the pdf report also ?

2022-12-22 14:58 UTC, ferran-S73 commented
> Hi. Thanks for this improvment. Could you apply changes on the pdf report also ?

Hey @legalsylvain added support for product images on pdf report too!

2022-12-22 15:44 UTC, legalsylvain commented
Hi. Thanks.
I'd like to test the feature on ruboat, but all the CI is red. (runboat, github actions). See : 
```
from PIL import Image, UnidentifiedImageError
ImportError: cannot import name 'UnidentifiedImageError'
```

Any idea ?

2022-12-22 15:54 UTC, ferran-S73 commented
> Hi. Thanks. I'd like to test the feature on ruboat, but all the CI is red. (runboat, github actions). See :
> 
> ```
> from PIL import Image, UnidentifiedImageError
> ImportError: cannot import name 'UnidentifiedImageError'
> ```
> 
> Any idea ?

Maybe it has to do with the version of PIL that's installed in the runboat? I'll check it out but I'm not sure I can do anything

2022-12-22 20:34 UTC, legalsylvain commented
- On github env, the version is displayed [in the log](https://github.com/OCA/product-attribute/actions/runs/3758786689/jobs/6387548834#step:4:144). It is : ``Pillow                                  5.4.1``
- It is the same version as the Odoo version. (see : https://github.com/odoo/odoo/blob/14.0/requirements.txt#L34)

So, I suspect that you use another more recent version of Pilow.

At the first sight, it seems ``UnidentifiedImageError`` that has been introduced [in version 7.0.0](https://github.com/python-pillow/Pillow/commit/40f891dfd70b484f7257fee455bd96f82f61d4e3)

2022-12-28 09:33 UTC, ferran-S73 commented
> * On github env, the version is displayed [in the log](https://github.com/OCA/product-attribute/actions/runs/3758786689/jobs/6387548834#step:4:144). It is : `Pillow                                  5.4.1`
> 
>     * It is the same version as the Odoo version. (see : https://github.com/odoo/odoo/blob/14.0/requirements.txt#L34)
> 
> 
> So, I suspect that you use another more recent version of Pilow.
> 
> At the first sight, it seems `UnidentifiedImageError` that has been introduced [in version 7.0.0](https://github.com/python-pillow/Pillow/commit/40f891dfd70b484f7257fee455bd96f82f61d4e3)

Hi @legalsylvain , I couldn't find anything equivalent of `UndefinedImageError` in v5.4.1 so I changed it to a general `Exception` as it should work as fine here

2022-12-28 10:26 UTC, legalsylvain commented
Yes, v5.4.1 seems quite old ! 
This will be fixed in more recent version : Version 9.0.1 is pinned for V16 that is quite recent (April 2022). 
- https://github.com/odoo/odoo/blob/16.0/requirements.txt#L24
- https://github.com/python-pillow/Pillow/tags

Thanks.

2023-05-03 06:23 UTC, ferran-S73 commented
@OCA/product-maintainers could you please review this pr or maybe remove the stale label please?

2023-06-22 16:20 UTC, legalsylvain approved these changes

2023-06-22 16:44 UTC, legalsylvain commented
Hi @ferran-S73. FYI, I'm migrating this module here : https://github.com/OCA/product-attribute/pull/1365

feel free to review this PR.

2023-06-22 21:11 UTC, pedrobaeza approved these changes
Please forward port it to v15

/ocabot merge major

2023-06-22 21:21 UTC, merged

2025-02-02 11:47 UTC, bosd commented
Todo Forward port to:
[ ] V 17
[ ] V 18