[WIP][15.0][ADD] product_supplierinfo_comment: New module
OCA/product-attribute pull request #1259
Opened 2023-01-23 14:18 UTC by sergio-teruel

cc @Tecnativa

2023-06-03 15:30 UTC, pedrobaeza commented
@sergio-teruel is this still WIP?

2023-10-09 06:42 UTC, pedrobaeza commented
@sergio-teruel

2024-01-11 19:49 UTC, bofiltd approved these changes
LGTM

2024-01-11 19:55 UTC, pedrobaeza commented
@OCA/board @etobella @sbidoul @dreispt @simahawk this person is approving massively pull requests without real reviews (it has approved about 20 in about 10 minutes). Not sure what are their intentions, but please discard and communicate about this abuse. If trying to scale in the "review ranking", it should be discarded.

2024-01-17 09:45 UTC, dreispt commented
Hello @bofiltd , indeed reviews should effectively either be code review or functional testing. Can you confirm this has been your approach?

2024-05-23 06:30 UTC, pedrobaeza requested changes

2024-05-23 06:30 UTC, pedrobaeza commented on product_supplierinfo_comment/__manifest__.py
> +    "license": "LGPL-3",
The header says `AGPL` but this puts `LGPL`. I think it's a mistake.

2024-05-23 07:59 UTC, sergio-teruel commented
Changes done!

2024-05-23 07:59 UTC, pedrobaeza approved these changes

2024-05-23 08:06 UTC, carlosdauden approved these changes

2024-05-23 08:07 UTC, pedrobaeza commented
/ocabot merge nobump

2024-05-23 08:16 UTC, merged