[14.0][IMP] test force default state on create
OCA/product-attribute pull request #1269
Opened 2023-02-15 14:26 UTC by Kev-Roche

When creating a new product, we can directly set a normal / sellable state on it, without validation. This PR avoid that by forcing the "_state_from" on product creation.

2023-02-15 17:53 UTC, Kev-Roche commented
Second commit fix it locally and on a project but not here. It seems that the search on  product.state return nothing in tests running here.  Any clue @dreispt , @sebastienbeau ?

2023-02-23 14:01 UTC, sebastienbeau requested changes

2023-02-23 14:01 UTC, sebastienbeau commented on product_tier_validation/models/product_template.py
> +        draft_state_id = self.env["product.state"].search(
it's not an id so name it "draft_state"

2023-02-23 14:07 UTC, sebastienbeau requested changes

2023-02-23 14:07 UTC, sebastienbeau commented on product_tier_validation/models/product_template.py
> +        return super().create(vals)
```suggestion
        return super().create(list_vals)
```

2023-02-23 14:07 UTC, sebastienbeau commented on product_tier_validation/models/product_template.py
> +        return super().create(vals)
```suggestion
    @api.model_create_multi
    def create(self, vals_list):
        states = self.env["product.state"].search([("code", "in", self._state_from)])
        if not states:
            raise UserError("Wrong configuration....")
        for vals in vals_list:
            if vals.get("product_state_id") not in states.ids:
                vals["product_state_id"] = states[0].id
        return super().create(list_vals)
```

2023-02-24 13:24 UTC, Kev-Roche commented on product_tier_validation/models/product_template.py
> +        draft_state_id = self.env["product.state"].search(
done

2023-02-24 13:24 UTC, Kev-Roche commented on product_tier_validation/models/product_template.py
> +        return super().create(vals)
done

2023-02-24 13:25 UTC, Kev-Roche commented on product_tier_validation/models/product_template.py
> +        return super().create(vals)
Thank you, I applide your suggestion.

2023-09-10 12:12 UTC, closed without merging

2023-11-21 05:22 UTC, sebastienbeau commented
@gurneyalex @rousseldenis can you reopen this PR? (I do not have the right to do it)

Thanks

2023-11-21 05:26 UTC, sebastienbeau reviewed
LGTM (code review) and tested