[MIG] product_weight : Migration to 16.0
OCA/product-attribute pull request #1328
Opened 2023-04-25 12:25 UTC by syera94

@florian-dacosta @bguillot 
A cron was added to the module.
The test have been changed to use some demonstration's products.

2023-04-25 12:51 UTC, legalsylvain requested changes
Hi. 

**Technical point** : I don't think that ``product_weight`` is a good name. too generic in my opinion. Something like ``product_weight_from_bom`` , ``bom_update_product_weight``, etc... or other name that should contain "bom".

**functional question** : You are using the ``weight`` field that is the brut weight. in a BoM context, the sum should be done on ``net_weight`` don't you think ?

the net weight was present in old version of odoo, but it has been removed for unknown reason. The field is now present in a OCA module.

- The module in v14 : https://github.com/OCA/product-attribute/tree/14.0/product_net_weight
- the module is being ported in v16 here : https://github.com/OCA/product-attribute/pull/1281

Nice to have : I guess that a button in the bom form to update the weight could be great. I mean, users are creating (or updating) bom, and when saving, want to update the weight at this step. Don't you think ?

2023-04-25 12:51 UTC, legalsylvain commented on product_weight/data/ir_cron_data.xml
> +        <field name="active" eval="True" />
Nice improvment. Could you set it to False by default ? (as some people does'nt want to have the cron enabled, and the cron could write bad data before user disable it)

2023-04-25 13:03 UTC, florian-dacosta commented
> Technical point : I don't think that product_weight is a good name. too generic in my opinion. Something like product_weight_from_bom , bom_update_product_weight, etc... or other name that should contain "bom".

I agree

> **functional question** : You are using the `weight` field that is the brut weight. in a BoM context, the sum should be done on `net_weight` don't you think ?

Well, that is a good question. In my opinion, this weight compute feature is really more adapter for phantom bom.
I have no case where I use this module with manufacturing, so I am not sure, but I think that for a manufactured BOM, it does not make much sense since you will probably scrap some material and the weight can't be the exact some of the component.

But for phantom (kit) bom, it make total sense, and I guess for this case, using the brut weight is fine.

So I wonder if we just adapt the cron so it recompute the weight only for phantom bom, maybe allowing to pass a domain if someone needs it for manufactured bom and think it will be consistent.

But I don't know if we want to force the use of the product_net_weight module to use this module.

2023-04-27 11:14 UTC, syera94 commented
@legalsylvain @florian-dacosta I changed the name fro product_weight to product_weight_from_bom. 
If needed, the nice to have can be done later.

2023-04-27 11:32 UTC, legalsylvain commented
>  If needed, the nice to have can be done later.

In that case, could you add a sentence in the ROADMAP.rst file ? 

otherwise, LGTM. Thanks !

2023-04-27 11:32 UTC, legalsylvain approved these changes

2023-04-27 12:23 UTC, legalsylvain reviewed
note : due to module renaming, you should renamed the .pot file and ``product_weight`` in the .po files I guess. Otherwise, translation will be lost.

2023-04-27 12:55 UTC, syera94 commented
@legalsylvain @florian-dacosta  done for the roadmap and done for the .po name change.

2023-06-07 09:12 UTC, hildickethan-S73 commented
![image](https://github.com/OCA/product-attribute/assets/47854752/c9c8014c-0864-472b-8330-126839ccf437)
to fit usual commit naming, i would suggest renaming the migration commit to `[MIG] product_weight: Migration to 16.0` and then squash the rest into the refactor commit where you rename it

2023-12-03 12:13 UTC, closed without merging