[16.0][ADD] product_company_default
OCA/product-attribute pull request #1412
Opened 2023-09-06 07:03 UTC by AungKoKoLin1997

2023-10-04 03:18 UTC, rinaldifirdaus approved these changes
Functional test: Work as expected!

2023-10-04 06:17 UTC, legalsylvain commented
Hi @AungKoKoLin1997 why product_dimension and product_company_default are incompatible ?

2023-10-04 06:53 UTC, AungKoKoLin1997 commented
> why product_dimension and product_company_default are incompatible ?

@legalsylvain I think this https://github.com/OCA/product-attribute/commit/cbb362c97a103d49420884749a0df24c7df4ae8b is the reason for product_dimension. For product_company_default, the product_company_default sets a default company during product creation, leading to incompatibilities with other module tests. Notably, in product_pricelist_supplierinfo, tests fail because pricelists are created with a default company set to "false," while products have the current company assigned, causing discrepancies and errors.

2023-10-06 08:31 UTC, yostashiro commented on product_company_default/models/product_template.py
> +    def _get_default_company(self):
I guess this is non-blocking but according to the convention: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#models
```suggestion
    def _default_company_id(self):
```

2023-10-06 08:31 UTC, yostashiro commented on product_company_default/readme/CONFIGURE.rst
> +To configure this module, you need to:
```suggestion
To enable the feature, you need to:
```

2023-10-06 08:31 UTC, yostashiro commented on product_company_default/readme/DESCRIPTION.rst
> +This module assigns default company to product.template.
```suggestion
This module populates the company field with user's company as the default value when creating new products.
```

2023-10-06 08:31 UTC, yostashiro commented on product_company_default/tests/test_product_company_default.py
> +        )
```suggestion
        product = self.env["product.product"].create({"name": "Test Product"})
```

2023-10-06 09:38 UTC, yostashiro commented on product_company_default/data/config_parameter.xml
> +        <field name="key">product.default_company_enable</field>
I think the key should start with the module name (as a convention).
```suggestion
        <field name="key">product_company_default.default_company_enable</field>
```

2023-10-06 12:22 UTC, yostashiro reviewed
@AungKoKoLin1997 Looks good. Please squash commits.

2023-10-06 12:41 UTC, legalsylvain requested changes
I think that the feature should be enabled by default. That is the expected behaviour, if people install the module. having an ir.config.parameter to enable it adds useless complexity. in data it should be "1"

However, we can disable it by demo data, to be sure there is no problem in demo / CI context. (can be "0")

2023-10-14 13:45 UTC, yostashiro approved these changes
Code review.

2023-10-14 17:05 UTC, legalsylvain approved these changes

2023-11-06 20:41 UTC, dreispt commented
/ocabot merge nobump

2023-11-06 21:10 UTC, merged