[ADD] product_packaging_level_purchasable
OCA/product-attribute pull request #1436
Opened 2023-10-23 06:04 UTC by santostelmo

2023-10-24 12:49 UTC, jbaudoux commented on product_packaging_level_purchasable/__manifest__.py
> +    "author": "Camptocamp, Odoo Community Association (OCA)",
```suggestion
    "author": "Camptocamp, BCIM, Odoo Community Association (OCA)",
```

2023-10-24 12:58 UTC, jbaudoux reviewed
LG. The boolean field name could be improved

2023-10-24 12:58 UTC, jbaudoux commented on product_packaging_level_purchasable/models/product_packaging.py
> +    purchases = fields.Boolean(
The field name could be improved
```suggestion
    can_be_purchased = fields.Boolean(
```

2023-10-24 12:58 UTC, jbaudoux commented on product_packaging_level_purchasable/models/purchase_order_line.py
> +                        "This product packaging must be set as 'Purchases' in"
```suggestion
                        "This product packaging must be set as 'Cab be purchased' in"
```

2023-10-24 12:58 UTC, jbaudoux commented on product_packaging_level_purchasable/readme/CONFIGURE.rst
> +  order line.
```suggestion
* Can be purchased: On a product packaging level as default value for a new product packaging. On a product packaging to make it available or not on a purchase order line.
```

2023-10-24 12:59 UTC, jbaudoux commented
This is inspired from https://github.com/OCA/product-attribute/pull/1395

2023-10-25 07:31 UTC, simahawk requested changes
pls address change requests

2023-10-25 07:31 UTC, simahawk commented on product_packaging_level_purchasable/models/product_packaging.py
> +        default=None,
```suggestion
```

2023-10-25 07:31 UTC, simahawk commented on product_packaging_level_purchasable/models/purchase_order_line.py
> +            if line._can_be_purchased_error_condition():
pls collect all lines failing before throwing an error

2023-10-25 09:58 UTC, santostelmo commented
@simahawk @jbaudoux changes done

2023-10-26 05:55 UTC, simahawk approved these changes
LGTM

2023-11-16 07:51 UTC, cyrilmanuel approved these changes

2023-11-16 11:13 UTC, simahawk commented
/ocabot merge nobump

2023-11-16 11:20 UTC, merged