[17.0][MIG] product_manufacturer: Migration to 17.0
OCA/product-attribute pull request #1462
Opened 2023-11-22 14:34 UTC by NICO-SOLUTIONS

Standard migration to 17.0

2023-11-22 21:35 UTC, pedrobaeza commented
/ocabot migration product_manufacturer

2023-12-09 12:36 UTC, smcqueen81 approved these changes
Funcional ok

2024-06-19 14:00 UTC, HviorForgeFlow approved these changes
Code review

2024-06-20 06:07 UTC, rousseldenis reviewed
Code review

2024-06-20 06:07 UTC, rousseldenis commented on product_manufacturer/models/product_template.py
> +        for template in self - unique_variants:
```suggestion
        (self - unique_variants).update({
            "manufacturer_id": False,
            "manufacturer_pname": False,
            "manufacturer_pref": False,
            "manufacturer_purl": False
        })
```

2024-06-20 06:07 UTC, rousseldenis commented on product_manufacturer/models/product_template.py
> +        for template in unique_variants:
```suggestion
        unique_variants.update({
            "manufacturer_id": (...),
            "manufacturer_pname": (...),
            "manufacturer_pref": (...),
            "manufacturer_purl": (...),
        })
```

2024-06-20 06:07 UTC, rousseldenis commented on product_manufacturer/models/product_template.py
> +                template.product_variant_ids.manufacturer_id = template.manufacturer_id
Same as above

2024-06-20 06:07 UTC, rousseldenis commented on product_manufacturer/tests/test_product_manufacturer.py
> +        cls.env = cls.env(context=dict(cls.env.context, tracking_disable=True))
FYI, Odoo has done it in a common test class now: https://github.com/odoo/odoo/blob/17.0/odoo/addons/base/tests/common.py#L21

2024-07-09 17:19 UTC, bizzappdev commented
@NICO-SOLUTIONS I have made the review changes https://github.com/NICO-SOLUTIONS/product-attribute/pull/1 to fast-track the process. Please check and proceed with the merge if it feels good.

2024-07-11 08:57 UTC, HviorForgeFlow commented
@rousseldenis all comments attended

2024-07-16 12:01 UTC, CasVissers-360ERP approved these changes
Functional review

2024-09-03 09:40 UTC, antoniocanovas approved these changes
Functional review OK !!

2024-09-11 07:54 UTC, Crazor commented
This one also appears to be stuck.

2024-09-23 16:21 UTC, rousseldenis requested changes

2024-09-23 16:21 UTC, rousseldenis commented on product_manufacturer/tests/test_product_manufacturer.py
> -        cls.env = cls.env(context=dict(cls.env.context, tracking_disable=True))
Either you let this, either you inherit from BaseCommon https://github.com/odoo/odoo/blob/17.0/odoo/addons/base/tests/common.py#L21

This allows to enhance tests performances.

2024-09-25 13:44 UTC, aessig commented
Looking forward for it to be merged

2024-11-25 11:17 UTC, StefanRijnhart commented
/ocabot merge nobump

2024-11-25 11:22 UTC, merged

2024-11-25 11:47 UTC, NICO-SOLUTIONS commented
@StefanRijnhart thx