[15.0][ADD] product_attachment_zipped_download: New module
OCA/product-attribute pull request #1570
Opened 2024-04-03 08:37 UTC by victoralmau

New module

![ejemplo](https://github.com/OCA/product-attribute/assets/4117568/05ceb152-ae2c-480f-881b-639bd6673a86)

@Tecnativa TT48578

2024-04-03 10:33 UTC, sergio-teruel approved these changes

2024-04-12 07:41 UTC, pedrobaeza requested changes
You need to add the option also for product.product, not only product.template.

2024-04-15 07:06 UTC, victoralmau commented
The option has been added to `product.product`.

2024-04-15 07:13 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2024-04-15 07:21 UTC, merged