[16.0][MIG] product_code_mandatory
OCA/product-attribute pull request #1575
Opened 2024-04-09 11:20 UTC by mariobinhex

Pending to CLA approving...
Improve test classes with **setUpClass**.
Last PR closed of migration module: [#1237](https://github.com/OCA/product-attribute/pull/1237).
Checked two last issues from [1230977029](https://github.com/OCA/product-attribute/pull/1237#pullrequestreview-1230977029).

2024-04-26 19:09 UTC, mgc-adhoc commented
LGTM Functional +1 @agyamuta @pedrocasi

2024-05-02 12:49 UTC, Bruno-Zanotti commented
Hey @mariobinhex could you squash migration commits?

2024-05-02 13:22 UTC, MarioLM-23 commented
> Hey @mariobinhex could you squash migration commits?

Done! I have maintained the pre-commit and migration

2024-05-31 14:54 UTC, mgc-adhoc commented
@OCA/product-maintainers could you please merge?
Thanks!

2024-06-28 14:55 UTC, florenciafrigieri2 commented
@rafaelbn Hello Rafal, can you please check this PR?

2024-07-16 13:26 UTC, jcadhoc commented
@rafaelbn hi Rafal, can you please check this PR and merge?

2024-07-16 13:28 UTC, jcadhoc commented
@simahawk hi Simone, can you please check this PR and merge? Thank you!

2024-07-18 08:58 UTC, simahawk requested changes
Thanks for your contrib.
Please check your history.
The migration commit contains changes to other modules and there's a merge commit that shouldn't be there.

Please, rebase on 16.0 instead and re-apply the migration commits.

2024-07-18 08:58 UTC, simahawk commented on product_code_mandatory/models/product.py
> +        "Internal Reference", index=True, default=_get_default_code
```suggestion
        "Internal Reference", index=True, default=lambda self: self._get_default_code()
```
To be done in a separated commit that can be back/fwd ported

2024-07-18 08:58 UTC, simahawk commented on product_code_mandatory/tests/test_product_code.py
> +class TestProductCode(TransactionCase):
```suggestion
from odoo.tests.common import BaseCommon


class TestProductCode(BaseCommon):
```
to disable tracking

2024-07-18 08:59 UTC, simahawk commented
/ocabot migration product_code_mandatory

2024-07-23 16:14 UTC, ced-adhoc commented
Hi @MarioLM-23 
Have you had a chance to address the request on the pr?
Thanks!

2024-07-26 20:22 UTC, closed without merging