[17][MIG] product_template_tags
OCA/product-attribute pull request #1581
Opened 2024-04-17 07:01 UTC by zurabkituashvili

tested according to this yt video tutorial: https://www.youtube.com/watch?v=3GdgM6bKSZQ

i migrated the addon from v16 to v17

2024-04-17 09:05 UTC, pedrobaeza commented
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

2024-07-19 08:56 UTC, traitrantrobz requested changes
Please, please, please follow [Migration-to-version-17.0]( https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0.). 
I don't know what you have added, removed, or edited. It's very difficult to review.

2024-07-23 09:32 UTC, nguyenminhchien commented
Hi, from the discovery of [grindtildeath](https://github.com/grindtildeath), we may no need this module anymore.
![image](https://github.com/user-attachments/assets/39fce4be-17cb-484a-9a72-7e8080da94d7)

2024-09-11 01:50 UTC, nilshamerlinck commented
https://github.com/OCA/product-attribute/issues/1446#issuecomment-2194753993

2025-02-16 12:20 UTC, closed without merging