[17.0] [MIG] product_print_category
OCA/product-attribute pull request #1607
Opened 2024-05-06 09:52 UTC by mariobinhex

Standar migration with changes in views and readme images

2024-05-06 13:24 UTC, legalsylvain requested changes
Hi. Thanks for porting this module @mariobinhex.

Suggestion inline. Otherwise, LGTM. Thanks !

2024-05-06 13:24 UTC, legalsylvain commented on product_print_category/views/view_product_print_category.xml
> +                            invisibile="product_qty == 0"
```suggestion
                            invisible="product_qty == 0"
```

2024-05-06 13:24 UTC, legalsylvain commented on product_print_category/views/view_product_print_category.xml
> +                        invisibile="product_to_print_qty == 0"
```suggestion
                        invisible="product_to_print_qty == 0"
```

2024-05-06 13:24 UTC, legalsylvain commented on product_print_category/views/view_product_print_category.xml
> +                        invisibile="product_qty == 0"
```suggestion
                        invisible="product_qty == 0"
```

2024-05-06 13:55 UTC, mariobinhex commented
@legalsylvain Done! Sorry for that mistake

2024-05-06 17:11 UTC, legalsylvain approved these changes
> @legalsylvain Done! Sorry for that mistake

No problem.

2024-08-30 08:26 UTC, dreispt approved these changes

2024-08-30 08:27 UTC, dreispt commented
/ocabot merge nobump

2024-08-30 08:32 UTC, merged