[16.0][ADD] product_template_default_weight
OCA/product-attribute pull request #1668
Opened 2024-06-21 18:55 UTC by mathieudelva

2025-01-06 14:56 UTC, emiliesoutiras approved these changes

2025-01-09 10:43 UTC, emiliesoutiras commented
Hi @Kev-Roche, @metaminux, 
Please, can you review it ?

2025-01-22 11:08 UTC, metaminux requested changes

2025-01-22 11:08 UTC, metaminux commented on product_template_default_weight/tests/test_weight_stock_picking.py
> +@tagged("post_install", "-at_install")
Why post_install here ?

2025-01-22 11:08 UTC, metaminux commented on product_template_default_weight/tests/test_weight_stock_picking.py
> +        picking_id = self.purchase_order_id.picking_ids
This module doesn't depends on purchase...

Should we add the dependency in __manifest__.py ?

2025-06-29 12:22 UTC, closed without merging