[17.0] [MIG] product_packaging_level_salable: Migration to 17.0
OCA/product-attribute pull request #1669
Opened 2024-06-24 09:45 UTC by bizzappdev

Dependency MR for module `product_packaging_level` https://github.com/OCA/product-attribute/pull/1662

2024-12-03 08:32 UTC, trisdoan approved these changes

2024-12-03 08:53 UTC, trisdoan requested changes
You need to remove migration script as well

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

2024-12-03 09:07 UTC, bizzappdev commented
> You need to remove migration script as well
> 
> https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

Removed. Thanks for noticing.

2025-01-30 12:21 UTC, ivantodorovich approved these changes

2025-01-30 12:21 UTC, ivantodorovich commented on product_packaging_level_salable/tests/test_packaging_level_can_be_sold.py
> +            self.assertIn("warning", onchange_res)
These lines are never tested because of the ValidationError just above.

Could you move this to a separate test method?

2025-01-30 12:21 UTC, ivantodorovich commented on product_packaging_level_salable/tests/test_packaging_level_can_be_sold.py
> +        with self.assertRaises(ValidationError):
nitpicking: use self.assertRaisesRegex and compare the actual error message

2025-02-04 11:52 UTC, bizzappdev commented
@ivantodorovich, changes are done.

2025-03-05 13:13 UTC, sebalix commented
/ocabot migration product_packaging_level_salable

2025-03-05 13:14 UTC, sebalix approved these changes
LG, can you remove the `[DON'T MERGE]` commit now that the dependency is merged? Thanks!

2025-03-05 13:23 UTC, bizzappdev commented
@sebalix test-requirement commit has been removed.

2025-03-06 15:44 UTC, bosd approved these changes

2025-03-10 07:26 UTC, sebalix commented
/ocabot merge nobump

2025-03-10 07:33 UTC, merged