[16.0][MIG] product_code_mandatory
OCA/product-attribute pull request #1693
Opened 2024-07-26 20:11 UTC by ced-adhoc

2024-07-26 20:19 UTC, pedrobaeza commented
/ocabot migration product_code_mandatory

2024-07-26 20:23 UTC, pedrobaeza commented
/ocabot migration product_code_mandatory

2024-07-31 12:04 UTC, florenciafrigieri2 approved these changes
Functional review, working ok. The internal reference is automatically fulfilled for the products and variants if it is empty.

2024-07-31 13:28 UTC, jcadhoc commented
@pedrobaeza Hi Pedro, Same case in this pr, i think we can merge.

2024-07-31 19:00 UTC, pedrobaeza requested changes
The migration commit contains changes that don't belong here, and the second commit, if they are migration reviews, should be squashed into the migration commit.

2024-08-01 15:22 UTC, ced-adhoc commented
> The migration commit contains changes that don't belong here, and the second commit, if they are migration reviews, should be squashed into the migration commit.

@pedrobaeza 
Reverted changes that don't belong to the module product_code_mandatory in the migration commit.

2024-08-01 19:59 UTC, pedrobaeza commented on README.md
> +[product_cost_security](product_cost_security/) | 16.0.1.2.0 | [![sergio-teruel](https://github.com/sergio-teruel.png?size=30px)]
I still see this incorrect change.

2024-08-02 13:24 UTC, ced-adhoc commented on README.md
> +[product_cost_security](product_cost_security/) | 16.0.1.2.0 | [![sergio-teruel](https://github.com/sergio-teruel.png?size=30px)]
Hi @pedrobaeza , it's fixed now, thanks

2024-08-02 14:43 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2024-08-02 14:52 UTC, merged