[17.0][MIG] product_pricelist_fixed_currency_rate: Migration to 17.0
OCA/product-attribute pull request #1702
Opened 2024-08-06 15:29 UTC by kobros-tech

I couldn't add my name in README file, but I added it in contributors file

2024-08-07 05:26 UTC, sanderlienaerts commented
Hi @kobros-tech, please make sure to run pre-commit before migrating. The changes made by pre-commit should come in front of your migration commit.

While you are migrating, you can add yourself as contributor in the readme folder and the contributor file. Pre-commit will run again during the pre-commit phase of your migration commit and one of the actions it will execute is to prepare the readme and module info.  

I haven’t looked at your changes, but will do once the commit with the pre-commit changes is present.

2024-08-07 12:57 UTC, kobros-tech commented
thanks for replying

I already tried am pre commit many times but it fails.

It genertes the readme file without my name as contributer.

the error is about .deb file and ar language as I think.

after pulling request 3 tests fail.

I am not aware about am and package management and I got exhausted really.

On Wed, Aug 7, 2024, 08:26 Sander Lienaerts ***@***.***>
wrote:

> Hi @kobros-tech <https://github.com/kobros-tech>, please make sure to run
> pre-commit before migrating. The changes made by pre-commit should come in
> front of your migration commit.
>
> While you are migrating, you can add yourself as contributor in the readme
> folder and the contributor file. Pre-commit will run again during the
> pre-commit phase of your migration commit and one of the actions it will
> execute is to prepare the readme and module info.
>
> I haven’t looked at your changes, but will do once the commit with the
> pre-commit changes is present.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/product-attribute/pull/1702#issuecomment-2272644759>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWIJXBGIOOLTI5LDOVWMM23ZQGVZ7AVCNFSM6AAAAABMCSYBFKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZSGY2DINZVHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-07 13:03 UTC, kobros-tech commented
I got these tests error, but I don't understand and don't know how to solve

https://github.com/OCA/product-attribute/actions/runs/10269617361/job/28415457597

https://github.com/OCA/product-attribute/actions/runs/10269617350/job/28415457560

On Wed, Aug 7, 2024, 15:55 mohamed alkobrosly ***@***.***>
wrote:

> thanks for replying
>
> I already tried am pre commit many times but it fails.
>
> It genertes the readme file without my name as contributer.
>
> the error is about .deb file and ar language as I think.
>
> after pulling request 3 tests fail.
>
> I am not aware about am and package management and I got exhausted really.
>
> On Wed, Aug 7, 2024, 08:26 Sander Lienaerts ***@***.***>
> wrote:
>
>> Hi @kobros-tech <https://github.com/kobros-tech>, please make sure to
>> run pre-commit before migrating. The changes made by pre-commit should come
>> in front of your migration commit.
>>
>> While you are migrating, you can add yourself as contributor in the
>> readme folder and the contributor file. Pre-commit will run again during
>> the pre-commit phase of your migration commit and one of the actions it
>> will execute is to prepare the readme and module info.
>>
>> I haven’t looked at your changes, but will do once the commit with the
>> pre-commit changes is present.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/OCA/product-attribute/pull/1702#issuecomment-2272644759>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AWIJXBGIOOLTI5LDOVWMM23ZQGVZ7AVCNFSM6AAAAABMCSYBFKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZSGY2DINZVHE>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-08-08 06:30 UTC, sanderlienaerts requested changes

2024-08-08 06:30 UTC, sanderlienaerts commented on product_pricelist_fixed_currency_rate/__init__.py
> +from .hooks import pre_init_hook, post_init_hook, uninstall_hook, post_load
You can see the changes you've made in commit https://github.com/OCA/product-attribute/pull/1702/commits/7c1ef7a91da0209ae6154c0df995d8f06c31a894. The line this comment is on, was added - yet there's no hooks folder and there are no hooks implemented for this module. To fix the issue you are having now with the tests, remove this line.

2024-08-08 06:30 UTC, sanderlienaerts commented on product_pricelist_fixed_currency_rate/views/pricelist_views.xml
> +                    'invisible': [('is_fixed_currency_rate_applicable', '=', False)]}"
The migration tasks have not been done. Please follow the tasks as mentioned in: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#tasks-to-do-in-the-migration

2024-08-08 06:32 UTC, sanderlienaerts commented
Before migrating, to not make things more difficult, please make sure to follow the steps in Technical method to migrate a module from "16.0" to "17.0" branch --> Full process. This ensures the pre-commit changes you need to do are present before the actual migration commit.

2024-08-08 14:11 UTC, kobros-tech commented
Hello Sander!

I am grateful to you for your advice.
I did what you have suggested and I still suffer from the same problem.

I took a snapshot to describe what is happening.



On Thu, Aug 8, 2024 at 9:32 AM Sander Lienaerts ***@***.***>
wrote:

> Before migrating, to not make things more difficult, please make sure to
> follow the steps in Technical method to migrate a module from "16.0" to
> "17.0" branch --> Full process. This ensures the pre-commit changes you
> need to do are present before the actual migration commit.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/product-attribute/pull/1702#issuecomment-2275053593>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWIJXBDKMGI6EQ2N7BBQJRTZQMGJFAVCNFSM6AAAAABMCSYBFKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZVGA2TGNJZGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-08 14:15 UTC, kobros-tech commented
also my name is not appened to the contributors q

On Thu, Aug 8, 2024, 17:11 mohamed alkobrosly ***@***.***>
wrote:

> Hello Sander!
>
> I am grateful to you for your advice.
> I did what you have suggested and I still suffer from the same problem.
>
> I took a snapshot to describe what is happening.
>
>
>
> On Thu, Aug 8, 2024 at 9:32 AM Sander Lienaerts ***@***.***>
> wrote:
>
>> Before migrating, to not make things more difficult, please make sure to
>> follow the steps in Technical method to migrate a module from "16.0" to
>> "17.0" branch --> Full process. This ensures the pre-commit changes you
>> need to do are present before the actual migration commit.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/OCA/product-attribute/pull/1702#issuecomment-2275053593>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AWIJXBDKMGI6EQ2N7BBQJRTZQMGJFAVCNFSM6AAAAABMCSYBFKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZVGA2TGNJZGM>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-08-08 22:11 UTC, closed without merging