[ADD][16.0] product_english_name module
OCA/product-attribute pull request #1732
Opened 2024-09-30 14:34 UTC by bealdav

2024-09-30 15:05 UTC, PaulGoubert approved these changes
Functionnal review OK

2024-10-01 21:59 UTC, bosd requested changes
Thanks for this attribution.
Some minor comments about warning and language.

Adittionally non blocking comment.
Compatability with product profile could be improved. As seen on runboat:
![image](https://github.com/user-attachments/assets/e0f6298e-e27d-47d2-93d3-14870cefbc1a)

2024-10-01 21:59 UTC, bosd commented on product_english_name/readme/CONFIGURE.rst
> +- active another language than english and set it to your user.
```suggestion
- activate another language than English and set it as your user language.
```

2024-10-01 21:59 UTC, bosd commented on product_english_name/readme/CONFIGURE.rst
> +- browse your products in form view.
```suggestion
- browse your products in a form view.
```

2024-10-01 21:59 UTC, bosd commented on product_english_name/readme/DESCRIPTION.rst
> +Product name is a very important information at least you buy products in a foreign country.
```suggestion
The Product name is very important information at least if you buy products in a foreign country.
```

2024-10-01 21:59 UTC, bosd commented on product_english_name/readme/DESCRIPTION.rst
> +This module can help to detect error on translations.
```suggestion
This module can help to detect those translation errors.
```

2024-10-01 21:59 UTC, bosd commented on product_english_name/views/product_template.xml
> +                <h5 groups="product_english_name.show_english_name">
```

2024-09-30 14:58:43,884 478 WARNING odoo odoo.addons.base.models.ir_ui_view: The group 'product_english_name.show_english_name' defined in view does not exist!
View error context:
{'file': '/__w/product-attribute/product-attribute/product_english_name/views/product_template.xml',
 'line': 3,
 'name': 'product.template form',
 'view': ir.ui.view(1841,),
 'view.model': 'product.template',
 'view.parent': ir.ui.view(464,),
 'xmlid': 'product_template_form_view'} 
```

2024-10-01 21:59 UTC, bosd commented on product_english_name/readme/DESCRIPTION.rst
> +    :alt: Display product name in english near name in user language
```suggestion
    :alt: Display the product name in English near the product name in users language
```

2024-10-01 21:59 UTC, bosd commented on product_english_name/security/groups.xml
> +        <field name="name">Show english name</field>
```suggestion
        <field name="name">Show English name</field>
```

2024-10-01 21:59 UTC, bosd commented on product_english_name/__manifest__.py
> +    "summary": """Display product name in english """,
```suggestion
    "summary": """Display the product name in English besides the product name in the users language. """,
```

2024-10-01 21:59 UTC, bosd commented on product_english_name/readme/DESCRIPTION.rst
> +This module display product name in english near name in user language.
```suggestion
This module displays the product name in English near the products name in user's language.
```

2024-10-01 21:59 UTC, bosd commented on product_english_name/readme/DESCRIPTION.rst
> +It often occurs that in an odoo instance product names don't match with their translations.
```suggestion
It often occurs that in an odoo instance the product names don't match with their translations.
```

2024-10-03 10:54 UTC, bealdav commented
Thanks a lot, @bosd for your review

2024-10-03 11:09 UTC, bealdav commented
![Uploading image.png…]()

Finally works

2024-10-03 11:28 UTC, Kev-Roche approved these changes
LGTM

2024-10-03 12:59 UTC, mourad-ehm approved these changes
Code review

2024-10-10 13:03 UTC, bealdav commented
Hi @bosd could you check again ?

2024-10-10 20:11 UTC, bosd approved these changes

2024-10-11 13:59 UTC, HaraldPanten commented
@bealdav You should squash your commits.

2024-10-11 14:31 UTC, bealdav commented
@HaraldPanten thanks to notified me. Fixed

2024-10-14 07:47 UTC, HaraldPanten commented
Hi, the commit name should appear without the version number, something like:

[ADD] product_english_name module: description in few words

2024-10-14 07:58 UTC, bealdav commented
@HaraldPanten where this rule is described ?

2024-10-14 08:00 UTC, pedrobaeza commented
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

2024-10-14 08:20 UTC, bealdav commented
I don't see in the doc, that it's required to not add version for an a new module.

But I'm ok to change my commit.

2024-10-14 09:17 UTC, HaraldPanten commented
> I don't see in the doc, that it's required to not add version for a new module.
> 
> But I'm ok to change my commit.

Hi @bealdav We have to follow Odoo's tags, and then apply OCA rules in case there are no examples ([MIG] is one of these use cases).

You can see that Odoo never uses the version number in the commit messages, as well --> https://github.com/odoo/odoo/pulls and here you can see Odoo's guidelines (for tagging) --> https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#tag-and-module-name

2024-10-14 09:47 UTC, bealdav commented
That's what I have applied, we're OK then
`[ADD] for adding new modules`

2024-10-14 09:48 UTC, bealdav commented
That seems to be nitpicking, but I'm OK to change my commit as said previously.
`You can see that Odoo never uses the version number in the commit messages`

2024-10-14 12:14 UTC, bealdav commented
Done, thanks for reviews

2024-10-14 12:16 UTC, PaulGoubert approved these changes

2024-10-14 14:54 UTC, HaraldPanten approved these changes
Didn't test the module in detail, but it has several reviews from other users, so... I'll try to help for moving forward.

THX for contributing!

2024-10-14 14:55 UTC, HaraldPanten commented
/ocabot merge nobump

2024-10-14 15:04 UTC, merged