[18.0][MIG] product_code_unique: Migration to 18.0
OCA/product-attribute pull request #1769
Opened 2024-11-13 15:28 UTC by pfranck

2024-11-27 16:45 UTC, sebalix approved these changes

2025-01-09 23:23 UTC, celm1990 requested changes
Please rebase the branch.
Squash administrative commits according this guide https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

2025-01-09 23:23 UTC, celm1990 commented on docker-compose.yml
Remove this file

2025-01-09 23:23 UTC, celm1990 commented on odoo.conf
Remove this file

2025-01-15 22:43 UTC, celm1990 commented
> Please rebase the branch. Squash administrative commits according this guide https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

@pfranck There are commits that can be squashed. Please review my previous comment.

2025-01-16 03:05 UTC, pfranck commented
> > Please rebase the branch. Squash administrative commits according this guide https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests
> 
> @pfranck There are commits that can be squashed. Please review my previous comment.

let me know if it's better now

2025-01-16 08:35 UTC, rousseldenis commented
/ocabot migration product_code_unique

2025-01-16 08:36 UTC, rousseldenis approved these changes

2025-02-04 20:55 UTC, celm1990 approved these changes
LGTM

2025-02-10 01:40 UTC, celm1990 commented
ping @sebalix @rousseldenis @pedrobaeza

2025-02-10 07:07 UTC, pedrobaeza commented
/ocabot merge nobump

2025-02-10 07:13 UTC, merged