17.0 mig product pricelist direct print
OCA/product-attribute pull request #1784
Opened 2024-11-26 09:42 UTC by therbin200

2025-01-22 18:24 UTC, bosd commented
@therbin200 Can you please fix pre-commit?

2025-01-22 18:57 UTC, bosd requested changes

2025-01-22 18:57 UTC, bosd commented on pandoc-3.5-1-amd64.deb
Please remove this file from your commit

2025-06-24 19:27 UTC, pedrobaeza commented
Superseded by #1971

2025-06-24 19:27 UTC, closed without merging