[18.0][MIG] product_packaging_type_required: Migration to 18.0
OCA/product-attribute pull request #1803
Opened 2024-12-05 10:04 UTC by trisdoan

### This change
- `doall` & `numbercall` fields were removed from ir_cron in https://github.com/odoo/odoo/pull/151628/commits/3a9949adbc87a1ca835aa7688e1f426b0ebbc8a8

2024-12-11 11:24 UTC, sebalix commented on product_packaging_type_required/models/product_packaging_type.py
> +    _inherit = "stock.package.type"
With this change:

- I would rename the file `stock_package_type.py`
- Should we also rename the module from `product_packaging_type_required` to `stock_package_type_required`, and move it in OCA/stock-logistics-warehouse alongside other `stock_package_type_*` modules (some in v16)?

cc @jbaudoux @rousseldenis

2024-12-11 11:24 UTC, sebalix commented on product_packaging_type_required/views/product_packaging_type_view.xml
>  <?xml version="1.0" encoding="UTF-8" ?>
This file can be renamed `stock_package_type.xml`

2024-12-11 11:43 UTC, jbaudoux requested changes
It's now package level. This is the one that needs to be marked as required.
Need to rename module to `product_packaging_level_required` and change models and filenames.

In v16, odoo integrated `stock.package.storage.type` as `stock.package.type`. And `product.packaging.type` has been renamed to `stock.packaging.level`.

2024-12-11 11:44 UTC, jbaudoux commented on product_packaging_type_required/models/product_packaging_type.py
> +    _inherit = "stock.package.type"
no, see my comment on the PR

2024-12-16 05:31 UTC, trisdoan commented
Hello @jbaudoux , @sebalix, I just updated the code, please help to take a look :pray:

2024-12-16 12:51 UTC, jbaudoux requested changes
I'm not fan of the module name. What about product_packaging_auto_create?

2024-12-16 12:51 UTC, jbaudoux commented on product_packaging_level_required/data/cron.xml
> +        <field ref="stock.model_stock_package_type" name="model_id" />
Should be level here also I guess

2024-12-16 12:51 UTC, jbaudoux commented on product_packaging_level_required/models/product_packaging_level.py
> +        """Create required packaging level for each consumable product if missing."""
It's product packing you are creating

2024-12-16 12:51 UTC, jbaudoux commented on product_packaging_level_required/models/product_packaging_level.py
>      required = fields.Boolean()
auto_create_packaging
Help: a cron will create a packaging for each product missing a packaging with this level

2024-12-30 16:34 UTC, jbaudoux approved these changes
LG. Can you reword commit with new module name `product_packaging_auto_create` as well as PR title

2024-12-30 20:40 UTC, jbaudoux requested changes
The design with the cron cannot work like that anymore because there is now a default=1 on the product packaging qty and a constraint that qty>0

I would park this PR for now as this cron is anyway not used anymore in prod.

2024-12-31 04:03 UTC, trisdoan commented
DRAFT: checking if any features can be added

2025-04-11 14:01 UTC, simahawk commented
@trisdoan @jbaudoux ping

2025-04-17 12:15 UTC, jbaudoux commented
In my opinion this is obsolete. For sales, it is up to the product manager to create properly the packaging. Otherwise it will be defined during reception (shopfloor_reception must handle that)

2025-04-30 11:22 UTC, jbaudoux commented
* https://github.com/OCA/wms/issues/1018

2025-05-06 08:43 UTC, closed without merging