[ADD] product_document_domain
OCA/product-attribute pull request #1817
Opened 2024-12-12 14:49 UTC by Tisho99

2024-12-12 15:33 UTC, Tisho99 commented
@ValentinVinagre @HaraldPanten

2024-12-16 16:08 UTC, sara-castello approved these changes
functional review LGTM

2024-12-17 07:32 UTC, manuelregidor requested changes

2024-12-17 07:32 UTC, manuelregidor commented on product_document_domain/models/product_product.py
> +                "default_res_model": self._name,
super method already returns "default_res_model": self._name in res["context"].

2024-12-17 07:32 UTC, manuelregidor commented on product_document_domain/models/product_product.py
> +                "default_res_id": self.id,
super method already returns "default_res_id": self.id in res["context"].

2024-12-17 07:32 UTC, manuelregidor commented on product_document_domain/models/product_product.py
> +    def _compute_product_document_count(self):
Have you thought of calling super and then adding the number of records that meet the domain  ("res_model", "=", "product.template"), ("res_id", "=", template.id)?

2024-12-17 07:32 UTC, manuelregidor commented on product_document_domain/models/product_template.py
> +    def _compute_product_document_count(self):
Kind of similar here. You could call super method and then reduce the records with domain ('res_model', '=', 'product.product'), ('res_id', 'in', template.product_variant_ids.ids). Has it been completely completely overriden for any specific reason?

2024-12-18 11:55 UTC, Tisho99 commented
@manuelregidor can you review again?

2024-12-18 12:07 UTC, manuelregidor approved these changes
Technical review. LGTM

2024-12-18 12:45 UTC, ValentinVinagre approved these changes
LGTM 👍🏻

2024-12-18 12:45 UTC, ValentinVinagre commented
@HaraldPanten could u review please?

2024-12-19 21:56 UTC, HaraldPanten approved these changes
LGTM

2024-12-19 21:56 UTC, HaraldPanten commented
/ocabot merge nobump

2024-12-19 22:02 UTC, merged