[18.0][MIG] product_category_active: Migration to 18.0
OCA/product-attribute pull request #1826
Opened 2024-12-27 06:00 UTC by HeliconiaSolutions

2025-01-08 13:23 UTC, yankinmax approved these changes

2025-01-15 10:53 UTC, StephaneMangin approved these changes

2025-01-16 11:17 UTC, simahawk commented
/ocabot migration product_category_active

You might want to fwd port this change https://github.com/OCA/product-attribute/pull/1834

2025-01-16 11:23 UTC, StephaneMangin commented
cc @HeliconiaSolutions Your PR is almost ready to merge. Just missing a minor fix. See @simahawk coments

2025-01-16 12:20 UTC, HeliconiaSolutions commented
@simahawk , @StephaneMangin , Thank you for your feedback. I have implemented the suggested fix. Could you please review it?

2025-01-16 13:53 UTC, sebalix requested changes
You didn't cherry-picked the commit done in https://github.com/OCA/product-attribute/pull/1834 but instead merge its content manually into your migration commit.

You should instead do:

    $ git cherry-pick c909d415962d57741b1e1d0ae1ba1cbd224deee5

Before your migration commit, then if this new code has to be adapted, you can do it in your migration commit as usual.

This is mandatory to preserve the git history.

2025-01-21 11:00 UTC, yankinmax commented
@StephaneMangin @sebalix let's speed up the migration. I've applied your request here:
- [ ] https://github.com/OCA/product-attribute/pull/1851

2025-01-24 06:47 UTC, sebalix commented
Thanks @yankinmax , closing this one then.

2025-01-24 06:47 UTC, closed without merging