[MIG][10.0] migrate product_sequence
OCA/product-attribute pull request #194
Opened 2016-10-24 13:43 UTC by SodexisTeam

Minor version change and renaming openerp to odoo imports

2016-10-24 17:15 UTC, pedrobaeza commented on product_sequence/README.rst
> +`here <https://github.com/OCA/product-attribute/issues/new?body=module:%20product_sequence%0Aversion:%2010.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20be
Use latest template: https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2016-10-24 17:16 UTC, pedrobaeza commented on product_sequence/data/product_sequence.xml
> +<odoo>
Use `<odoo noupdate="1"/>`

2016-10-24 17:16 UTC, pedrobaeza requested changes
2 things commented.

2016-10-25 06:33 UTC, atchuthan commented
@pedrobaeza fixed your comments

2016-10-25 06:38 UTC, pedrobaeza approved these changes

2016-10-25 08:20 UTC, gurneyalex approved these changes

2016-10-25 08:20 UTC, merged