[9.0][ADD] product_pricelist_simulation: Show price in product for all pricelists
OCA/product-attribute pull request #222
Opened 2017-01-12 09:50 UTC by sergio-teruel

cc @Tecnativa

2017-01-15 13:31 UTC, pedrobaeza requested changes

2017-01-15 13:31 UTC, pedrobaeza commented on product_pricelist_simulation/models/product.py
> +        self.ensure_one()
Make it multi record aware

2017-01-27 09:51 UTC, bealdav commented
I like the idea of your module, nice, but I think it could be better (for performance with really big db) to have access these infos with 'more options' button than directly in the form.
Maybe it could be a choice settings ?

Thanks a lot to Tecnativa one more time

2017-01-27 10:43 UTC, sergio-teruel commented
@bealdav Thanks for yor feedback, I have on mind this improvement... I have to finish tests, and I will do more changes...
OK?? :smile:

2018-06-28 19:03 UTC, pedrobaeza commented
Closing as no more interest in this

2018-06-28 19:03 UTC, closed without merging