[PORT] Port customer_context_in_product_view to V10
OCA/product-attribute pull request #246
Opened 2017-03-28 22:36 UTC by gdgellatly

Is a cleaner PR from #245 rebased onto 10.0. Just the customer context files.

2017-03-29 09:23 UTC, pedrobaeza commented
Now that I re-visit this module, I think that a better name is _product_customer_pricing_, as the main area is product, and this reflects in less words the feature. What do you think?

2017-03-29 10:01 UTC, gdgellatly commented
@pedrobaeza Lol that was pretty much the original name. I had to change to
get module accepted in first place. I hate the current name so happy to
change.

On Wed, 29 Mar 2017, 10:23 PM Pedro M. Baeza, <notifications@github.com>
wrote:

> Now that I re-visit this module, I think that a better name is
> *product_customer_pricing*, as the main area is product, and this
> reflects in less words the feature. What do you think?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/product-attribute/pull/246#issuecomment-290033572>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AE23kJ1DKzAmjTVPTyHouwYg4yQD4iMKks5rqiL3gaJpZM4MsR8w>
> .
>

2017-03-29 10:02 UTC, pedrobaeza commented
Really? And it was me who told you about the change? I'm crazy... :stuck_out_tongue_closed_eyes:

2017-03-29 23:49 UTC, gdgellatly commented
@pedrobaeza I don't remember now, was years ago.  Anyhow I changed the name to customer_pricing_in_product_view which pretty well explains the module and roadmap.

2017-04-01 15:29 UTC, pedrobaeza requested changes

2017-04-01 15:29 UTC, pedrobaeza commented on customer_pricing_in_product_view/README.rst
> +Navigate to a customer (form view)
Put a numbered list with `#.`

2017-04-01 15:29 UTC, pedrobaeza commented on customer_pricing_in_product_view/README.rst
> +Previous versions of this module allowed the customers name to be typed directly in the view.
Put this into a bullet list prepending points with `*`

2017-04-01 15:29 UTC, pedrobaeza commented on customer_pricing_in_product_view/README.rst
> +While fields.dummy has been deprecated the functionality can still be acheived by an unstored many2one
s/acheived/achieved

2017-04-01 15:29 UTC, pedrobaeza commented on customer_pricing_in_product_view/README.rst
> +If these issues are resolved and there is a way to get
Is this half redacted?

2017-04-01 15:29 UTC, pedrobaeza commented on customer_pricing_in_product_view/__manifest__.py
> +    'author': "Odoo Community Association (OCA)",
You should include yourself in the author list

2017-04-01 15:29 UTC, pedrobaeza commented on customer_pricing_in_product_view/models/res_partner.py
> +##############################################################################
Use short headers like the one in https://github.com/OCA/maintainer-tools/blob/master/template/module/__init__.py

2017-04-11 23:23 UTC, gdgellatly commented
@pedrobaeza changes as requested

2017-05-16 16:31 UTC, lasley approved these changes

2017-05-16 16:35 UTC, pedrobaeza approved these changes

2017-05-16 16:35 UTC, merged