[10.0][FIX] product_uom: Fix all data fields.
OCA/product-attribute pull request #248
Opened 2017-03-28 23:36 UTC by bmw95

* Change to factor_inv where uom_type is bigger
* 10.0 PR for #247 
* @lasley

2017-03-28 23:57 UTC, lasley approved these changes

2017-03-28 23:57 UTC, lasley commented
cc @max3903

2017-03-29 00:04 UTC, max3903 requested changes
:+1: 

@bmw95 Liter is twice in the list of UoM with the same configuration. Can you remove it from this module?

2017-03-29 02:03 UTC, bmw95 commented
@max3903 Thanks! Liter has been removed.

2017-03-29 04:53 UTC, merged