[10.0] add new module to manage seasonal products
OCA/product-attribute pull request #262
Opened 2017-05-05 16:09 UTC by Cedric-Pigeon

Coming from https://github.com/OCA/product-attribute/pull/117 and adapted to V10

Depends on https://github.com/OCA/product-attribute/pull/261

2017-07-25 13:36 UTC, lreficent commented on product_life_period/README.rst
> +* Go to ...
Could you fill this?

2017-07-25 13:36 UTC, lreficent commented on product_life_period/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/135/8.0
10.0

2020-12-11 17:37 UTC, rousseldenis commented
@Cedric-Pigeon Is this still applicable ?

2020-12-14 06:15 UTC, Cedric-Pigeon commented
@rousseldenis Yes we still use it

2020-12-14 07:47 UTC, rousseldenis requested changes
Code review. Some comments

2020-12-14 07:47 UTC, rousseldenis commented on product_life_period/__manifest__.py
> +    "website": "http://www.acsone.eu",
Please change this key

2020-12-14 07:47 UTC, rousseldenis commented on product_life_period/models/product_life_period.py
> +            end_life_period.product_ids.write({'state': 'end'})
Build product ids set and write on all once.

2020-12-22 10:56 UTC, rousseldenis commented
@LoisRForgeFlow Could you update your review ?

2020-12-22 11:07 UTC, rousseldenis approved these changes

2021-01-04 08:18 UTC, lmignon approved these changes
Thank you @Cedric-Pigeon  LGTM (Code review only)

2021-03-23 10:14 UTC, rousseldenis commented
/ocabot merge patch

2021-03-23 11:27 UTC, merged