[REF] product_customer_code, product_supplierinfo_for_customer: Changes in README
OCA/product-attribute pull request #282
Opened 2017-06-28 14:59 UTC by ysantiago

2017-07-06 14:22 UTC, moylop260 approved these changes
👍 
This README update help us to avoid create changes that won't be approved.

(Like as us from https://github.com/OCA/product-attribute/pull/276)

2017-07-06 14:22 UTC, moylop260 commented
@JulioSerna @elicoidal What do you think about?

2017-07-06 15:15 UTC, JulioSerna approved these changes

2017-07-07 00:37 UTC, elicoidal requested changes
some details

2017-07-07 00:37 UTC, elicoidal commented on product_customer_code/README.rst
> +**NOTE**: This module is overlapped by `product_supplierinfo_for_customer
do you mean superseded?

2017-07-07 00:37 UTC, elicoidal commented on product_customer_code/README.rst
> +<../product_supplierinfo_for_customer>`_
I dont think the URL can work all the time. You need to specify absolute path for both.

2017-07-07 01:15 UTC, ysantiago commented on product_customer_code/README.rst
> +<../product_supplierinfo_for_customer>`_
@elicoidal The suggested changes were applied.

2017-07-07 01:24 UTC, elicoidal approved these changes

2017-07-07 01:24 UTC, merged