[REF] product_supplierinfo_for_customer_sale: Return all result in name_search, products found by default code and customer code
OCA/product-attribute pull request #283
Opened 2017-06-30 04:21 UTC by ysantiago

2017-07-03 16:24 UTC, ysantiago commented
@JulioSerna @moylop260 can you please review this change?

2017-07-03 16:50 UTC, moylop260 commented on product_supplierinfo_for_customer_sale/models/product_product.py
> +              supplierinfo.mapped('product_tmpl_id.id'))],
`s/supplierinfo.mapped('product_tmpl_id.id')/supplierinfo.mapped('product_tmpl_id').ids/g`

2017-07-03 16:52 UTC, moylop260 commented on product_supplierinfo_for_customer_sale/models/product_product.py
> +        # list(set()) to delete repeated records (if exist)
Remove this comment (The code is obvious that delete repeated)

2017-07-03 16:53 UTC, moylop260 commented on product_supplierinfo_for_customer_sale/models/product_product.py
> +        return list(set(res + product.name_get()))
Use `res.extend(product.name_get())` in order to use the same pointer

2017-07-03 16:53 UTC, moylop260 requested changes
Please, add a test case where a result returns 2 or more items

2017-07-03 20:32 UTC, ysantiago commented
@moylop260 please, can you see the changes?

2017-07-04 02:15 UTC, moylop260 approved these changes

2017-07-04 02:27 UTC, moylop260 commented on product_supplierinfo_for_customer_sale/models/product_product.py
> +        return list(set(res))
Sorry, just one more change... 
in order to improvement the performance here we should use this transformation just if is really need it.
So IMHO is better use:
```python
if products:
    res.extend(products.name_get())
    res = list(set(res))
return res
```


We can save a lot of seconds by method executed, you could calculate it with:
```bash
python -m timeit -s "res=[(1, 'A'),(2, 'B'),(3, 'C'),(2, 'B'),]" "res=list(set(res))"
1000000 loops, best of 3: 0.596 usec per loop
```

2017-07-04 02:35 UTC, moylop260 commented on product_supplierinfo_for_customer_sale/models/product_product.py
>               ('product_name', operator, name)])
If not supplierinfo:
    return res

2017-07-04 02:41 UTC, moylop260 commented on product_supplierinfo_for_customer_sale/models/product_product.py
> +        return list(set(res))
Or better...
Use a `product_ids = set(supplierinfo.mapped('product_tmpl_id').ids) - set([id for id, name in res])` from search call method.

And reduce the limit from current res.
`limit=limit - len(res)`

And you will have unique products with exactly the number of records defined and you will save a lot of time reducing the query.

2017-07-04 02:43 UTC, moylop260 commented on product_supplierinfo_for_customer_sale/tests/test_product_name_search.py
> +            'product_code': 'code_test_1',
Use the `product.default_code` to return 2 records
One from supplier info and other one from product default search.

2017-07-04 02:52 UTC, moylop260 requested changes
sorry other changes

2017-07-04 16:28 UTC, moylop260 commented on product_supplierinfo_for_customer_sale/tests/test_product_name_search.py
> +
remove useless change

2017-07-04 16:30 UTC, moylop260 approved these changes
👍 
Thanks!

@JulioSerna 
What do you think about?

2017-07-04 18:05 UTC, JulioSerna approved these changes

2017-07-04 19:49 UTC, moylop260 commented
@elicoidal 
What do you think about?

2017-07-05 04:20 UTC, elicoidal approved these changes
LGTM

2017-07-05 04:20 UTC, merged