[9.0][IMP] product_pricelist_direct_print: Add order option
OCA/product-attribute pull request #290
Opened 2017-09-04 09:12 UTC by carlosdauden

@Tecnativa

2017-09-04 12:32 UTC, pedrobaeza requested changes
Please add Spanish translation as well

2017-09-06 15:13 UTC, rafaelbn approved these changes
Tested functionally in runbot 👍 Thanks!

2017-09-06 15:13 UTC, rafaelbn commented on product_pricelist_direct_print/views/report_product_pricelist.xml
> +                            </t>
Minor style remark
![2017-09-06_17-08-57](https://user-images.githubusercontent.com/8736623/30119607-95ef5514-9326-11e7-92bc-b4d83453826e.png)

2017-11-28 16:12 UTC, luismontalba approved these changes
Tested on runbot

2018-02-19 17:46 UTC, carlosdauden commented
@rafaelbn Changes done

2018-02-19 17:55 UTC, carlosdauden commented
@pedrobaeza Changes done

2018-02-23 15:21 UTC, pedrobaeza approved these changes

2018-02-23 15:22 UTC, merged