11.0 imp product_pricelist_direct_print
OCA/product-attribute pull request #396
Opened 2018-10-23 12:48 UTC by ernestotejeda

* Print price list for future date
* Print price list for N last ordered products
* Send report by email to each partner selected

Cc @Tecnativa

2018-11-23 11:38 UTC, sergio-teruel requested changes

2018-11-23 11:38 UTC, sergio-teruel commented on product_pricelist_direct_print/wizards/product_pricelist_print.py
> +                res['pricelist_id'] = partner.property_product_pricelist.id
```suggestion
                res['pricelist_id'] = partner.property_product_pricelist.id
        elif self.env.context.get('active_model') == 'product.pricelist.item':
            active_ids = self.env.context.get('active_ids', [])
            items = self.env['product.pricelist.item'].browse(active_ids)
            if items[:1].applied_on == '0_product_variant':
                res['show_variants'] = True
                res['product_ids'] = [(6, 0, items.mapped('product_id').ids)]
            else:
                res['product_tmpl_ids'] = [
                    (6, 0, items.mapped('product_tmpl_id').ids)]               
```

2018-11-23 11:38 UTC, sergio-teruel commented on product_pricelist_direct_print/wizards/product_pricelist_print.py
> +                res['pricelist_id'] = partner.property_product_pricelist.id
Can you add this code? is for print from pricelist items..
Thanks

2018-11-23 11:38 UTC, sergio-teruel commented on product_pricelist_direct_print/wizards/product_pricelist_print.py
> +            return False
Remove this condition to allow send email from any model

2018-11-23 11:38 UTC, sergio-teruel commented on product_pricelist_direct_print/wizards/product_pricelist_print.py
> +            'partner_to': self.partner_id,
Remove partner_to key

2018-11-23 11:38 UTC, sergio-teruel commented on product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
> +                </page>
```suggestion
                </page>
                <page string="Customers">
                    <field name="partner_ids"/>
                    <field name="partner_count" invisible="1"/>
                </page>                
```

2018-11-23 11:38 UTC, sergio-teruel commented on product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
> +                </page>
Allow select partners.

2018-11-23 11:38 UTC, sergio-teruel commented on product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
> +
```suggestion

<act_window id="action_item_pricelist_print"
    key2="client_print_multi"
    name="Price List"
    res_model="product.pricelist.print"
    src_model="product.pricelist.item"
    groups="product.group_sale_pricelist"
    view_mode="form" target="new" view_type="form"/>

```

2018-11-23 11:38 UTC, sergio-teruel commented on product_pricelist_direct_print/wizards/product_pricelist_print_view.xml
> +
Print from pricelists items

2018-11-27 09:37 UTC, sergio-teruel commented
ping @ernestotejeda

2018-11-27 16:31 UTC, ernestotejeda commented
Thanks @sergio-teruel, I have made almost all the changes you propose except the ones related with pricelist items because I don't know where I can find their corresponding tree view to be able to test those changes.
When you talk about selecting several partners, to be consistent with the behavior of the module should be sent to each one an email with the report corresponding to the associated price list, and therefore I have added some other things like, Once at least one partner is selected, the pricelists in the wizard is not visible, and some details about the visibility of the fields I changed too.

2018-11-27 22:59 UTC, pedrobaeza commented
You can rebase this PR now that I have merged the other one.

2018-11-28 09:17 UTC, chienandalu commented
Well there's no such pricelist item list view :sweat_smile:

2018-11-28 09:59 UTC, chienandalu reviewed
I can't make multiple partner send work on runbot:

![image](https://user-images.githubusercontent.com/5040182/49144046-a8a70a80-f2fc-11e8-8f6a-16e347d7df2f.png)

2018-11-29 15:46 UTC, ernestotejeda commented
@chienandalu is true that in *Settings -> Technical -> Email -> Messages* the corresponding messages have the field *Recipients* empty, but emails are sent correctly.
If you test with incorrect addresses you will see in *Settings -> Technical -> Email -> Emails* that the emails have the field *To (Partners) * correctly, but if you test with correct addresses, emails are deleted but those ones are sent correctly .
Apparently this is the behavior of mass mailing. When module *mass_mailing* is installed and you send a newsletter you will see the same behavior.

2018-12-01 09:11 UTC, pedrobaeza commented
> Thanks @sergio-teruel, I have made almost all the changes you propose except the ones related with pricelist items because I don't know where I can find their corresponding tree view to be able to test those changes.

@ernestotejeda this is because in standard there's no such view... unless you go to the model in *Settings > Technical > Database structure > Model*, find that model, and add menu item. Please do it and add the suggested code.

2018-12-04 11:17 UTC, chienandalu commented
@ernestotejeda I'm trying to PR to your repo this commit improving the pricelist items print but I can't find your fork: https://github.com/Tecnativa/product-attribute/commit/7bbc7a43915c38eafee863fba94d343188948eae

- Sets the pricelist in the wizard if all the items belong to the same one.
- Lets to print items applied on different rules altogether.

ping @sergio-teruel

2018-12-21 16:58 UTC, chienandalu approved these changes

2018-12-21 17:10 UTC, pedrobaeza approved these changes
I don't like too much to have you fields `partner_id` and `partner_ids` for the same thing, as you can check if `len(partner_ids) == 1`, but for not blocking this more time and not doing diff bigger, let's merge it this way.

2018-12-21 17:15 UTC, merged