[12.0] [MIG] product_firmware_version
OCA/product-attribute pull request #427
Opened 2019-01-29 17:21 UTC by Nikul-Chaudhary

Product firmware version
========================

This module allows you to store the latest/official/tested firmware version on an electronic product.

2019-02-06 18:39 UTC, Nikul-Chaudhary commented
@OCA/product-maintainers could you please review code?

2019-04-13 07:10 UTC, Nikul-Chaudhary commented
@pedrobaeza @bodedra Could you please review it?

2019-04-26 09:47 UTC, tbaden requested changes
thanks for the work 👍 
code lgtm
just a minor detail

2019-04-26 09:47 UTC, tbaden commented on product_firmware_version/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
please use the new README by fragment system and generate the README.rst with the [maintainer-tools](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0)

2019-06-20 11:08 UTC, Nikul-Chaudhary commented
@tbaden @bodedra Code you please review again?

2019-07-23 06:27 UTC, bodedra approved these changes
Tested on Runbot. LGTM :+1: 

@Nikul-Chaudhary Thanks for migration.

2019-09-11 05:46 UTC, Nikul-Chaudhary commented
@pedrobaeza @rafaelbn Can you please review and move forward.

2019-12-06 07:21 UTC, Nikul-Chaudhary commented
@pedrobaeza @rafaelbn @max3903 if you don't mind, can you please review it?

2020-02-10 09:04 UTC, emagdalenaC2i approved these changes
LGTM

2020-02-28 06:52 UTC, simahawk commented
/ocabot merge

2020-02-28 17:37 UTC, merged