[12.0][MIG] product_supplierinfo_for_customer
OCA/product-attribute pull request #515
Opened 2019-10-15 12:28 UTC by mreficent

Supersede of https://github.com/OCA/product-attribute/pull/446.

2019-10-15 17:35 UTC, pedrobaeza requested changes

2019-10-15 17:35 UTC, pedrobaeza commented on product_supplierinfo_for_customer/models/product_template.py
>      supplier_ids = fields.One2many(
Do you need to keep the definition of these fields?

2019-10-15 17:35 UTC, pedrobaeza commented on product_supplierinfo_for_customer/__manifest__.py
>          "purchase",
Why this one depends on purchase? I don't think the module must depend on it, and more wanting to use it for customers

2019-10-15 17:35 UTC, pedrobaeza commented on product_supplierinfo_for_customer/security/ir.model.access.csv
> +access_product_customerinfo_purchase_manager,product.customerinfo purchase_manager,model_product_customerinfo,purchase.group_purchase_manager,1,1,1,1
This should be removed when stripping purchase dependency.

2019-10-15 17:35 UTC, pedrobaeza commented on product_supplierinfo_for_customer/views/product_view.xml
>                  <group attrs="{'invisible': [('product_variant_count','&lt;=',1)]}">
I think you are able to remove most of these overwrites with the refactoring. Take also into account the Odoo paradigm of not splitting variants supplierinfo with template ones.

2019-10-15 17:35 UTC, pedrobaeza commented on product_supplierinfo_for_customer/migrations/12.0.1.0.0/post-migration.py
> +        env['product.supplierinfo'].browse(ids).unlink()
Do it on SQL

2019-10-15 17:35 UTC, pedrobaeza commented on product_supplierinfo_for_customer/migrations/12.0.1.0.0/post-migration.py
> +                AsIs(rename[0]),
Use new `sql.SQL` syntax. It's much better than this. Or at least use a dictionary, as this is very hard to be understood with indexes.

2019-10-23 09:34 UTC, pedrobaeza requested changes

2019-10-23 09:34 UTC, pedrobaeza commented on product_supplierinfo_for_customer/models/product_customerinfo.py
> +class CustomerInfo(models.Model):
According guidelines, it should be `ProductCustomerInfo`

2019-10-23 09:34 UTC, pedrobaeza commented on product_supplierinfo_for_customer/models/product_customerinfo.py
> +        'res.partner', 'Customer',
We don't need to redefine all the attributes. Put only the redefined ones (string, domain and help).

2019-10-23 09:34 UTC, pedrobaeza commented on product_supplierinfo_for_customer/models/product_template.py
> +    seller_ids = fields.One2many(
Why do we need to keep this? I think you shouldn't override the label and leave the standard one, which is "Vendors". Even more, this one in singular is not appropriated IMO.

2019-10-23 09:34 UTC, pedrobaeza commented on product_supplierinfo_for_customer/models/product_template.py
> +    variant_seller_ids = fields.One2many(
Same reasoning about label for this one

2019-10-23 09:34 UTC, pedrobaeza commented on product_supplierinfo_for_customer/migrations/12.0.1.0.0/post-migration.py
> +            "DELETE"
Missing spaces between words

2019-10-23 09:34 UTC, pedrobaeza commented on product_supplierinfo_for_customer/migrations/12.0.1.0.0/post-migration.py
> +        other_fields += ' purchase_requisition_line_id,'
This is not the way to do it. See below.

2019-10-23 09:34 UTC, pedrobaeza commented on product_supplierinfo_for_customer/migrations/12.0.1.0.0/post-migration.py
> +            "WHERE id in %s", (tuple(ids), )
Delete directly by the original condition (type = 'customer'), not by IDs

2019-10-23 09:34 UTC, pedrobaeza commented on product_supplierinfo_for_customer/migrations/12.0.1.0.0/post-migration.py
> +        INSERT INTO product_customerinfo (
You mustn't insert specific fields, but copy full structure and then move full record. This way, you don't need to worry by any possible extension to the model.

See https://github.com/OCA/contract/blob/a0e118c97570dc1c3cef7df236c714d30ee547b6/contract/migrations/12.0.4.0.0/pre-migration.py#L90-L103 as example for this.

2019-10-23 09:34 UTC, pedrobaeza commented on product_supplierinfo_for_customer/migrations/12.0.1.0.0/post-migration.py
> +        openupgrade.logged_query(
Due to the new approach, this code is needed for initializing sequence:
```python
    cr.execute("CREATE SEQUENCE IF NOT EXISTS product_customerinfo_id_seq")
    cr.execute("SELECT setval('product_customerinfo_id_seq', "
               "(SELECT MAX(id) FROM product_customerinfo))")
    cr.execute("ALTER TABLE product_customerinfo ALTER id "
               "SET DEFAULT NEXTVAL('product_customerinfo_id_seq')")
```

2019-10-23 20:54 UTC, pedrobaeza requested changes
The statement
```
CREATE TABLE ... (LIKE ... INCLUDING ALL)
```
is missing. Without it, no constraints are copied, so the table is half built. Please include it.

2019-10-24 09:55 UTC, MiquelRForgeFlow commented
@pedrobaeza But the table has been created before during install. The migration file is post-migration, not pre-migration.

2019-10-24 09:57 UTC, pedrobaeza commented
You must do this in pre-migration, not post

2019-10-24 11:08 UTC, AaronHForgeFlow approved these changes
Functional tests with several customers and prices  LGTM :+1:

2019-10-24 15:51 UTC, pedrobaeza approved these changes

2019-10-24 15:51 UTC, pedrobaeza commented
/ocabot merge

2019-10-24 16:43 UTC, merged