[WIP][MIG][12.0] product_cost_security: Migration to v12.0
OCA/product-attribute pull request #533
Opened 2019-11-29 14:54 UTC by sergio-teruel

2019-11-29 15:25 UTC, chienandalu approved these changes
Tested. :+1:

2019-11-29 19:33 UTC, pedrobaeza requested changes

2019-11-29 19:33 UTC, pedrobaeza commented on product_cost_security/__manifest__.py
> +    'development_status': 'Production/Stable',
You need to declare `maintainers` if promoting to stable

2019-12-03 14:37 UTC, sergio-teruel commented
Changes done!!

2019-12-03 15:26 UTC, pedrobaeza approved these changes

2019-12-03 15:26 UTC, pedrobaeza commented
/ocabot merge

2019-12-03 16:27 UTC, merged