[13.0][MIG] product_template_tags
OCA/product-attribute pull request #542
Opened 2019-12-20 11:09 UTC by ps-tubtim

2020-02-06 15:27 UTC, lfreeke requested changes
This is working but I think it should have a menu option to manage the tags.

2020-02-07 12:56 UTC, i-vyshnevska commented
@lfreeke there is menu called  "Product Tags"

2020-02-07 12:56 UTC, i-vyshnevska approved these changes

2020-02-10 08:31 UTC, emagdalenaC2i commented on product_template_tags/views/product_template.xml
> +            <xpath expr="//page[@name='general_information']" position="inside">
See #568

2020-02-10 09:07 UTC, lfreeke commented
@i-vyshnevska You are totally correct! I would have expected it somewhere else.

2020-02-10 09:07 UTC, lfreeke approved these changes

2020-02-11 02:29 UTC, ps-tubtim commented on product_template_tags/views/product_template.xml
> +            <xpath expr="//page[@name='general_information']" position="inside">
Thank you. Edited.

2020-02-11 21:38 UTC, emagdalenaC2i approved these changes
LGTM

2020-02-12 19:04 UTC, patrickrwilson approved these changes
LGTM

2020-02-13 07:32 UTC, simahawk commented
/ocabot merge

2020-02-13 07:58 UTC, merged