[WIP][MIG][13.0] product_pricelist_direct_print: Migration y
OCA/product-attribute pull request #562
Opened 2020-02-01 19:23 UTC by sergio-teruel

2020-02-01 22:31 UTC, legalsylvain commented
@sergio-teruel, Travis tests related to your module are not passing. Could you check ?

2020-02-02 08:32 UTC, sergio-teruel commented
Fixed!! Although the module coverage is low...

2020-02-02 09:04 UTC, legalsylvain commented
You can improve it, checking the the result of the call of ``message_composer_action`` and ``get_last_ordered_products_to_print`` (see : https://codecov.io/gh/OCA/product-attribute/compare/d66fc5d8bbb9e08d4ccf50f713107953cd648d3c...bd8eb83a2b3509cf7ffc7a44d97ba0114b817bec/diff)

2020-02-03 16:50 UTC, Tardo requested changes

2020-02-03 16:50 UTC, Tardo commented on product_pricelist_direct_print/readme/CONFIGURE.rst
> +#. Set *Multiple Sales Prices per Product* on an either
```suggestion
#. Enable 'Pricelists'
```

2020-02-03 16:50 UTC, Tardo commented on product_pricelist_direct_print/readme/CONFIGURE.rst
> +   *Multiple prices per product* or *Prices computed from formulas*
```suggestion
```

2020-02-03 16:50 UTC, Tardo commented on product_pricelist_direct_print/readme/CONFIGURE.rst
> +   *Multiple prices per product* or *Prices computed from formulas*
Can be good add a warning that the group 'Advanced Pricelists' is needed.

2020-02-03 16:50 UTC, Tardo commented on product_pricelist_direct_print/readme/USAGE.rst
> +#. Go to *Sales > Catalog > Print Price List*
```suggestion
#. Go to *Sales > Products > Print Price List*
```

2020-02-03 16:50 UTC, Tardo commented on product_pricelist_direct_print/readme/USAGE.rst
> +#. Go to *Sales > Catalog > Products*
```suggestion
#. Go to *Sales > Products > Products*
```

2020-02-03 16:50 UTC, Tardo commented on product_pricelist_direct_print/readme/USAGE.rst
> +#. Go to *Sales > Catalog > Product Variants*
```suggestion
#. Go to *Sales > Products > Product Variants*
```

2020-02-03 16:50 UTC, Tardo commented on product_pricelist_direct_print/readme/USAGE.rst
> +#. Go to *Sales > Orders > Customers**
```suggestion
#. Go to *Sales > Product > Customers**
```

2020-02-03 16:50 UTC, Tardo commented on product_pricelist_direct_print/readme/USAGE.rst
> +    * Press *Print > Price List*
I can't see this options

2020-02-04 09:25 UTC, sergio-teruel commented
@Tardo @legalsylvain Changes done!!

2020-02-05 13:32 UTC, Tardo requested changes

2020-02-05 13:32 UTC, Tardo commented on product_pricelist_direct_print/readme/CONFIGURE.rst
> +#. Enable *Pricelists* > *Advanced price rules*.
```suggestion
#. Enable *Pricelists*

Users will need *Advanced Pricelists* to access menus:

#. Enable developer mode
#. Go to *Settings > Users & Companies > Users*
#. Create or Edit a record
#. Scroll to *Technical Settings*
#. Enable *Advanced Pricelists*
```

2020-02-05 13:32 UTC, Tardo commented on product_pricelist_direct_print/readme/USAGE.rst
> +    * Press *Print > Price List*
This is shown in "Action" menu... not in "Print" :/

2020-02-05 13:32 UTC, Tardo commented on product_pricelist_direct_print/readme/USAGE.rst
> +#. Go to *Sales > Orders > Customers**
See this

2020-02-17 20:36 UTC, sergio-teruel commented
@Tardo Changes done!

2020-02-18 09:43 UTC, carlosdauden approved these changes
Code and functional review LGTM
Fix precommit error

2020-02-28 06:44 UTC, simahawk commented
@Tardo ping
@sergio-teruel the build needs some love ;)

2020-02-28 15:39 UTC, Tardo approved these changes
:+1: LGTM, only non-blocking comments

2020-02-28 15:39 UTC, Tardo commented on product_pricelist_direct_print/wizards/product_pricelist_print.py
> +        res = super(ProductPricelistPrint, self).default_get(fields)
```suggestion
        res = super().default_get(fields)
```

2020-02-28 15:39 UTC, Tardo commented on product_pricelist_direct_print/wizards/product_pricelist_print.py
> +            return self.message_composer_action()
Can reduce complexity...
```suggestion
            self.send_batch()
            return
        if self.partner_count == 1:
            partner = self.partner_ids[0]
            self.write(
                {
                    "partner_id": partner.id,
                    "pricelist_id": partner.property_product_pricelist.id,
                }
            )
        return self.message_composer_action()
```

2020-02-29 09:12 UTC, sergio-teruel commented
@Tardo changes done!!

2020-03-05 11:11 UTC, emagdalenaC2i approved these changes
Code LGTM, just small comments

2020-03-05 11:11 UTC, emagdalenaC2i commented on product_pricelist_direct_print/wizards/product_pricelist_print.py
> +            # Convert al pricelist items to their affected templates
```suggestion
            # Convert all pricelist items to their affected templates
```

2020-03-05 11:11 UTC, emagdalenaC2i commented on product_pricelist_direct_print/wizards/product_pricelist_print.py
> +            # Convert al pricelist items to their affected variants
```suggestion
            # Convert all pricelist items to their affected variants
```

2020-03-05 11:11 UTC, emagdalenaC2i commented on product_pricelist_direct_print/wizards/product_pricelist_print.py
> +            "view_type": "form",
I think you can delete this line, rigth?

2020-03-05 11:24 UTC, sergio-teruel commented
Ok.. @emagdalenaC2i changes done!!

2020-03-05 18:48 UTC, emagdalenaC2i commented
/ocabot merge

2020-03-05 18:52 UTC, pedrobaeza commented
Isn't this missing the latest changes in previous versions?

2020-03-05 18:59 UTC, emagdalenaC2i commented on product_pricelist_direct_print/views/report_product_pricelist.xml
> +                <h2>Price List</h2>
@pedrobaeza All changes in #581 are implemented except this line that was deleted.
But, I am not sure that it should be deleted

2020-03-05 19:04 UTC, pedrobaeza commented
And what about #499 and #501?

2020-03-05 19:10 UTC, emagdalenaC2i commented
No, those PRs have not yet migrated to v12. As I mentioned here https://github.com/OCA/product-attribute/pull/581#issuecomment-592173058

2020-03-05 19:14 UTC, pedrobaeza commented
That's why I ask to migrate it here too before merging.

2020-05-25 05:26 UTC, simahawk commented
@sergio-teruel are you going to attend https://github.com/OCA/product-attribute/pull/562#issuecomment-595398358 then?

2020-05-25 08:36 UTC, sergio-teruel commented
@simahawk Last comments attended and added lost PR's

2020-05-25 08:40 UTC, sergio-teruel commented
Rebase done!!

2020-05-29 07:35 UTC, simahawk commented
@pedrobaeza good for you?

2020-06-01 06:08 UTC, ventor-dev commented
@pedrobaeza , is it ok to be merged?

2020-06-01 06:43 UTC, pedrobaeza commented
/ocabot merge nobump

2020-06-01 08:11 UTC, merged