[MIG] product_weight: Migration to 13.0
OCA/product-attribute pull request #618
Opened 2020-05-23 08:27 UTC by tonygalmiche

Do not review at this time. I'm just starting the migration.

2020-05-23 10:52 UTC, bealdav requested changes
Thanks for your contribution

2020-05-23 10:52 UTC, bealdav commented on product_weight/tests/test_compute_bom_weight.py
> +        super(TestBomWeightCompute, self).setUp()
In python 3

```suggestion
        super().setUp()
```

2020-05-23 10:52 UTC, bealdav commented on product_weight/wizard/product_weight_update.py
> +        res = super(ProductWeightUpdate, self).default_get(fields)
```suggestion
        res = super().default_get(fields)
```

2020-05-23 10:52 UTC, bealdav commented on product_weight/models/__init__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
Headers in an empty file are useless

2020-05-23 10:52 UTC, bealdav commented on product_weight/readme/CONTRIBUTORS.rst
> +* Thore Baden <thorebaden@gmail.com>
@tonygalmiche you should add you name/mail here

2020-05-23 11:21 UTC, tonygalmiche commented
Thank you @bealdav for your review. It's corrected

2020-05-23 12:37 UTC, bealdav approved these changes

2020-05-26 15:16 UTC, hparfr approved these changes
LGTM

2020-05-26 15:29 UTC, tonygalmiche commented
Thank you @hparfr  for your review

2020-06-17 21:04 UTC, dreispt commented
/ocabot merge nobump

2020-06-19 16:09 UTC, pedrobaeza commented
@dreispt ocabot stuck on merge

2020-06-19 16:35 UTC, rousseldenis commented
> @dreispt ocabot stuck on merge

Relaunched it. Switching to travis github app should solve webhook trigger problems like this.

2020-06-19 16:41 UTC, rousseldenis commented
/ocabot merge nobump

2020-06-19 17:09 UTC, merged