[ADD] product_pricelist_assortment
OCA/product-attribute pull request #633
Opened 2020-06-17 10:08 UTC by benwillig

@rousseldenis You might want to take a look

2020-06-17 11:19 UTC, Cedric-Pigeon approved these changes
LGTM. I would just fill CONTRIBUTOR.rst and DESCRIPTION.rst

2020-06-17 11:27 UTC, acsonefho approved these changes
LGTM!

2020-06-19 06:46 UTC, rousseldenis requested changes
Some comments

2020-06-19 06:46 UTC, rousseldenis commented on product_pricelist_assortment/__manifest__.py
> +    "website": "https://acsone.eu",
Change to https://github.com/OCA/product-attribute

See https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py

2020-06-19 06:46 UTC, rousseldenis commented on product_pricelist_assortment/models/product_pricelist_assortment_item.py
> +        self.ensure_one()
Make it as a real multi

2020-06-19 06:46 UTC, rousseldenis commented on product_pricelist_assortment/models/product_pricelist_assortment_item.py
> +            PricelistItem.create(item_value)
Use create multi (list of values)

2020-06-19 06:46 UTC, rousseldenis commented on product_pricelist_assortment/models/product_pricelist.py
> +            item_assortment._update_assortment_items()
See comment here under about multi()

2020-06-19 06:46 UTC, rousseldenis commented on product_pricelist_assortment/models/product_pricelist_assortment_item.py
> +    name = fields.Char(related="assortment_filter_id.name", readonly=True,)
No need of readonly (default)

2020-06-19 07:01 UTC, benwillig commented
Updated the website key @rousseldenis, for the other requested changes, feel free to create a new PR or to push on this one

2020-06-19 07:53 UTC, Cedric-Pigeon commented
@benwillig I think @rousseldenis proposal totally makes sense to speed up performances. It is not so complicated to do. Could you please reconsider?

2020-06-22 14:04 UTC, rousseldenis approved these changes
Code review

2020-07-19 08:32 UTC, dreispt commented
/ocabot merge nobump

2020-07-19 11:00 UTC, merged