[MIG] product_multi_price: Migration to 12.0
OCA/product-attribute pull request #639
Opened 2020-06-25 13:58 UTC by chienandalu

- Minor migration tweaks

cc @Tecnativa TT23610

2020-06-25 14:17 UTC, pedrobaeza requested changes
And please squash administrative commits in the closest upper one

2020-06-25 14:17 UTC, pedrobaeza commented on product_multi_price/tests/test_product_multi_price.py
> +        cls.prod_prod_2_1.update({
```suggestion
        cls.prod_prod_2_1.write({
```

2020-06-25 14:17 UTC, pedrobaeza commented on product_multi_price/tests/test_product_multi_price.py
> +        cls.prod_prod_2_2.update({
```suggestion
        cls.prod_prod_2_2.write({
```

2020-06-25 14:36 UTC, chienandalu commented
@pedrobaeza Changes done

2020-06-25 14:43 UTC, pedrobaeza approved these changes
Supposing Travis is green

2020-06-29 12:38 UTC, ernestotejeda reviewed
Thanks David.
Just a little issue:

![Peek 2020-06-29 08-33](https://user-images.githubusercontent.com/38267832/86006226-a8dd1f80-b9e3-11ea-9a81-ccc1f09c6b1c.gif)

2020-06-30 06:30 UTC, chienandalu commented
> Just a little issue:

Looks like this issue is in v11 as well and comes from some incompatibility of the selection widget for the multi price many2one and the pricelist item auto generated for the pricelist when the pricelist is in state new.

Any ideas @Yajo @Tardo @pedrobaeza ?

2020-06-30 06:47 UTC, pedrobaeza commented
selection widget for m20 is not working in tree views (I thought that was modified in v11 already...). Change that widget.

2020-06-30 06:55 UTC, chienandalu commented
> selection widget for m2o is not working in tree views

It's on a form and it works fine once the pricelist is saved.

2020-06-30 07:17 UTC, Yajo commented on product_multi_price/views/product_pricelist_views.xml
> +                <field name="multi_price_name" colspan="6" attrs="{'invisible': [('base', '!=', 'multi_price')], 'required': [('base', '=', 'multi_price')]}" widget="selection"/>
As @pedrobaeza said, it seems [you cannot use the selection widget in a m2o field](https://github.com/odoo/odoo/blob/7ea6798fb8b8b0249f56cf4bc5cab627438cd636/addons/web/static/src/js/fields/relational_fields.js#L2352):

```suggestion
                <field name="multi_price_name" colspan="6" attrs="{'invisible': [('base', '!=', 'multi_price')], 'required': [('base', '=', 'multi_price')]}" />
```

2020-06-30 07:42 UTC, chienandalu commented
Ok. Changes done

2020-07-01 16:04 UTC, Tardo commented on product_multi_price/models/product_template.py
> +        if vals.get('price_ids'):
Why need rewrite this field?

2020-07-03 16:56 UTC, pedrobaeza commented on product_multi_price/models/product_template.py
> +        if vals.get('price_ids'):
Clarified in a docstring in the code:
```
Overwrite creation for rewriting the prices (if set and having only
one variant), after the variant creation, that is performed in super.
```

2020-07-03 17:00 UTC, Tardo approved these changes

2020-07-03 17:01 UTC, pedrobaeza commented
/ocabot merge nobump

2020-07-03 17:34 UTC, merged