[14.0][MIG]product_state
OCA/product-attribute pull request #725
Opened 2020-11-17 05:49 UTC by watthanun

2020-12-11 15:52 UTC, rousseldenis requested changes
Code review.

2020-12-11 15:52 UTC, rousseldenis commented on product_state/tests/test_product_state.py
> +        # print(self.state.products_count)
Please remove the comments and logger

2020-12-19 20:51 UTC, andreampiovesana approved these changes
go

2020-12-21 21:06 UTC, andreampiovesana approved these changes
i am using in production
go

2021-02-09 10:36 UTC, andreampiovesana commented
you should chang manifest
"application": False,

2021-03-08 20:24 UTC, bosd commented
@watthanun Are you going to finish this one? Please look at the commits so V14 changes are in the V14 migration commit.

2021-03-10 14:55 UTC, ferranmateu approved these changes
Functional review OK but better quit it from Applications

2021-03-16 08:08 UTC, rousseldenis commented
@watthanun @kittiu Do you plan to finish this one ?

2021-03-16 09:32 UTC, rousseldenis commented
@watthanun @kittiu I did a PR on your repo to fix this and add some tests https://github.com/ecosoft-odoo/product-attribute/pull/2

2021-03-16 09:45 UTC, kittiu commented
> @watthanun @kittiu I did a PR on your repo to fix this and add some tests [ecosoft-odoo#2](https://github.com/ecosoft-odoo/product-attribute/pull/2)

Ok. Really sorry. I will merge yours.

2021-03-16 09:53 UTC, rousseldenis commented
> > @watthanun @kittiu I did a PR on your repo to fix this and add some tests [ecosoft-odoo#2](https://github.com/ecosoft-odoo/product-attribute/pull/2)
> 
> Ok. Really sorry. I will merge yours.

No problem, this way is good too. I think I will add another one too for some improvements (tracking and one index)

2021-03-17 08:21 UTC, rousseldenis commented
@Cedric-Pigeon @emagdalenaC2i I think the state should be required if the module is installed.

The values for existing products are initialized through the init_hook and there is a default now.

What do you think ?

2021-03-29 01:22 UTC, emagdalenaC2i approved these changes

2021-04-28 07:37 UTC, rousseldenis commented
@kittiu Could you fix pre-commit, so we can go forward on this ?

2021-04-28 08:30 UTC, kittiu commented
> @kittiu Could you fix pre-commit, so we can go forward on this ?

Done, thanks!

2021-05-05 06:42 UTC, rousseldenis approved these changes

2021-05-07 16:45 UTC, dreispt commented
/ocabot merge nobump

2021-05-07 20:37 UTC, merged