[14.0][MIG]product_packaging_dimension
OCA/product-attribute pull request #736
Opened 2020-12-08 07:08 UTC by watthanun

2020-12-11 15:28 UTC, rousseldenis approved these changes
Code review. A test would be helpful.

2020-12-11 15:28 UTC, rousseldenis commented on product_packaging_dimension/models/product_packaging.py
> +            pack.volume = (pack.lngth * pack.width * pack.height) / 1000.0 ** 3
IMHO, it's time to add a little test for this

2021-01-25 09:38 UTC, atchuthan requested changes

2021-01-25 09:38 UTC, atchuthan commented on product_packaging_dimension/models/product_packaging.py
> +    height = fields.Integer("Height (mm)", help="height in millimeters")
The fields are already available in product.packaging
https://github.com/odoo/odoo/blob/14.0/addons/delivery/models/product_packaging.py

2021-02-08 09:27 UTC, hparfr commented
I think it's better to not hardcode UoM.

A similar work has been done in this PR https://github.com/OCA/product-attribute/pull/775

2021-03-29 13:46 UTC, claudiagn approved these changes
LGTM! :+1: 

https://user-images.githubusercontent.com/61511679/112846095-f20eec80-90a5-11eb-98d5-36797495f7ff.mp4

2021-04-26 07:31 UTC, rousseldenis commented
@watthanun @kittiu Could we switch to the more recent one : https://github.com/OCA/product-attribute/pull/850 ?

2021-04-26 09:10 UTC, kittiu commented
> @watthanun @kittiu Could we switch to the more recent one : #850 ?

Can you help close this one. Watthanun is no longer here. Thanks @rousseldenis

2021-04-26 09:16 UTC, closed without merging