[11.0][MIG] product pricelist tier
OCA/product-attribute pull request #746
Opened 2020-12-11 11:32 UTC by dsolanki-initos

2020-12-11 15:14 UTC, rousseldenis requested changes
Code review. Minor change

2020-12-11 15:14 UTC, rousseldenis commented on product_pricelist_tier/__manifest__.py
> +    "website": "http://www.initos.com",
Please follow OCA conventions here.

2021-02-23 12:51 UTC, fshah-initos approved these changes

2021-03-08 04:50 UTC, dsolanki-initos commented
we abort the work because of newer available Odoo versions.

2021-03-08 04:50 UTC, closed without merging