[13.0][ADD] product_uom_volumetric_weight: Add Product Uom Volumetric Weight
OCA/product-attribute pull request #889
Opened 2021-07-22 07:58 UTC by victoralmau

This module extends the functionality of product_dimension to add Volumetric weight in products.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT30722

2021-07-22 08:49 UTC, pedrobaeza commented
If this finally depends on `product_dimension`, shouldn't it be `product_dimension_volumetric_weight`?

2021-07-22 10:44 UTC, chienandalu reviewed
¿No support for variants?

2021-07-23 09:50 UTC, hparfr commented
Hi,

May be a dumb question but, why there is no weight in the formula of volumetric_weight ? 

About the UI, the unit of "volumetric_weight" is not explicit. Shoulnd't it be "dimensional_uom / Kg" ?

2021-07-27 06:20 UTC, victoralmau commented
Changes done.
IMO volumetric weight is need to be added in extra addon because `product_dimension` is only related to dimension and field name is correct.

2021-07-28 12:59 UTC, chienandalu approved these changes

2021-07-28 15:42 UTC, pedrobaeza requested changes
Add also configure file (and generate README), stating how to set the ratio at UoM.

2021-07-28 15:42 UTC, pedrobaeza commented on product_dimension_volumetric_weight/models/product.py
> +    def _compute_weight_volumetric(self):
No need to repeat this method if it's the same as upstream `product.template` one.

2021-07-28 15:42 UTC, pedrobaeza commented on product_dimension_volumetric_weight/readme/DESCRIPTION
> +This module extends the functionality of product_dimension to add Volumetric weight in products.
```suggestion
This module extends the functionality of product_dimension to add Volumetric weight in products.

It's used for example by some carrier agencies to compute the cost price of the delivery service.
```

2021-07-28 15:42 UTC, pedrobaeza commented on product_dimension_volumetric_weight/tests/test_product_uom.py
> +        product_form.product_width = 1
This is testing a functionality of other module, so no need to include it here.

2021-07-28 15:42 UTC, pedrobaeza commented on product_dimension_volumetric_weight/tests/test_product_uom.py
> +        product_form.product_width = 60
Again testing something that is not of this module. Why don't you set `volume` and just that?

2021-07-28 15:42 UTC, pedrobaeza commented on product_dimension_volumetric_weight/models/product.py
> +class ProductProduct(models.Model):
Split both models in their corresponding files.

2021-07-28 15:42 UTC, pedrobaeza commented on product_dimension_volumetric_weight/models/product.py
> +        digits="Volume",
This is weight, not volume.

2021-07-28 15:42 UTC, pedrobaeza commented on product_dimension_volumetric_weight/models/product.py
> +        readonly=True,
A compute is always readonly

2021-07-28 17:42 UTC, pedrobaeza commented
Another thing: why fields are called `weight_volumetric`, but the module is `volumetric_weight`. The only reasoning I see is for having together `weight` and `weight_volumetric`, but not sure if that reason is important enough for having this duality in the name. What others think about this?

2021-07-29 06:18 UTC, victoralmau commented
> Another thing: why fields are called `weight_volumetric`, but the module is `volumetric_weight`. The only reasoning I see is for having together `weight` and `weight_volumetric`, but not sure if that reason is important enough for having this duality in the name. What others think about this?

Yes, probably `volumetric_weight` is the better option to field names.

2021-07-29 08:00 UTC, rousseldenis approved these changes
Code review

2021-07-29 16:23 UTC, pedrobaeza approved these changes

2021-07-29 16:24 UTC, pedrobaeza commented
/ocabot merge nobump

2021-07-29 17:54 UTC, merged