[14.0][ADD] uom_extra_data: have mm, ml, week, work week uom
OCA/product-attribute pull request #915
Opened 2021-10-06 03:34 UTC by HoKhanhNguyen99

2021-10-18 09:54 UTC, hparfr requested changes
Some requests to be more consistent and clear.


About __work__ week: 5 or 7 days are both work week.

2021-10-18 09:54 UTC, hparfr commented on uom_extra_data/data/uom.xml
> +    <record id="product_uom_mm" model="uom.uom">
```suggestion
    <record id="product_uom_millimeter" model="uom.uom">
```
because more explicit

2021-10-18 09:54 UTC, hparfr commented on uom_extra_data/data/uom.xml
> +    <record id="product_uom_week" model="uom.uom">
product_uom_7d_week

2021-10-18 09:54 UTC, hparfr commented on uom_extra_data/data/uom.xml
> +    <record id="product_uom_work_week" model="uom.uom">
product_uom_5d_week

2021-10-18 09:54 UTC, hparfr commented on uom_extra_data/data/uom.xml
> +    <record id="product_uom_milliliter" model="uom.uom">
```suggestion
    <record id="product_uom_millilitre" model="uom.uom">
```

(because of `uom.product_uom_litre`)

2021-10-21 08:19 UTC, nguyenhk99 commented
> Some requests to be more consistent and clear.
> 
> About **work** week: 5 or 7 days are both work week.

Good day @hparfr , I just changed it.  Thanks for review.

2021-10-22 15:14 UTC, ajaniszewska-dev approved these changes

2021-10-22 15:16 UTC, hparfr approved these changes

2021-11-09 11:59 UTC, dreispt commented
/ocabot merge nobump

2021-11-10 07:53 UTC, nilshamerlinck commented
Hi @dreispt would you mind trying the merge again?

2021-11-12 14:21 UTC, rousseldenis commented
/ocabot merge patch

2021-11-12 14:49 UTC, merged