15.0 mig product supplierinfo for customer
OCA/product-attribute pull request #934
Opened 2021-11-04 18:29 UTC by nalejhandro

2021-11-10 23:15 UTC, nalejhandro commented
Hi @pedrobaeza  can you help me with a review of this migration?

2021-11-10 23:16 UTC, pedrobaeza commented
Sorry, not working on this right now.

2021-11-12 14:09 UTC, rousseldenis requested changes
Code review

2021-11-12 14:09 UTC, rousseldenis commented on product_supplierinfo_for_customer/models/product_product.py
> +        ).sorted(lambda s: (s.sequence, s.min_qty, s.price, s.id))
@nalejhandro Why changing the order from previous version ?

EDIT: Ok, saw the commit message. Could you maybe put that change in a separate commit ?

2021-11-12 14:09 UTC, rousseldenis approved these changes

2021-11-25 17:13 UTC, hugho-ad approved these changes

2021-11-25 17:53 UTC, CarmenMiranda commented
Hi, @moylop260 @luisg123v Could your take a look at this?

This was already approved twice 😃

2021-11-25 21:23 UTC, moylop260 commented
/ocabot merge nobump

2021-11-25 21:57 UTC, moylop260 commented
/ocabot merge nobump

2021-11-25 22:01 UTC, merged