[13.0][ADD] product_attribute_archive
OCA/product-attribute pull request #937
Opened 2021-11-09 12:53 UTC by AlvaroTForgeFlow

Backport from v14 to v13 of the product_attribute_archive module.

2021-11-10 08:49 UTC, AlvaroTForgeFlow commented
Hi @JordiBForgeFlow  , could I have a review here?

2021-11-11 13:20 UTC, HviorForgeFlow commented
@OCA/product-maintainers can you  approve running workflow, thanks!

2021-11-11 15:03 UTC, rousseldenis approved these changes
Code review

2021-11-11 15:32 UTC, HviorForgeFlow requested changes
@AlvaroTForgeFlow

2021-11-11 15:32 UTC, HviorForgeFlow commented on product_attribute_archive/views/product_attribute.xml
> +            <field name="active" optional="hide" />
Unable to show column active on product.attribute form, you should apply to place that column inside the Attribute Value tree

```suggestion
            <xpath expr="//field[@name='value_ids']/tree" position="inside">
              <field name="active" optional="hide"/>
            </xpath>
```

2021-11-11 15:39 UTC, HviorForgeFlow commented on product_attribute_archive/views/product_attribute.xml
> +            <field name="active" optional="hide" />
Rebase required to fix pre-commit

2021-11-12 11:43 UTC, HviorForgeFlow approved these changes
Functional review LGTM :+1:

2021-11-17 09:04 UTC, MiquelRForgeFlow approved these changes
code LGTM

2021-11-23 18:56 UTC, rousseldenis commented
/ocabot merge patch

2021-11-23 20:00 UTC, merged