[14.0][MIG] product_supplierinfo_revision: Migration to 14.0
OCA/product-attribute pull request #940
Opened 2021-11-10 13:14 UTC by victoralmau

Migration to 14.0

Please @joao-p-marques and @CarlosRoca13 can you review it?

@Tecnativa TT31817

2021-11-10 15:13 UTC, CarlosRoca13 approved these changes

2021-11-11 12:43 UTC, rousseldenis requested changes
Code review

2021-11-11 12:43 UTC, rousseldenis commented on product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard.py
> +        for item in Supplierinfo.browse(self.env.context["active_ids"]):
```suggestion
        for item in Supplierinfo.browse(self.env.context.get("active_ids")):
```

2021-11-11 12:43 UTC, rousseldenis commented on product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard.py
> +        action = self.env.ref("product.product_supplierinfo_type_action").read()[0]
```suggestion
        action = self.env["ir.actions.actions"]._for_xml_id("product.product_supplierinfo_type_action")
```

2021-11-11 12:43 UTC, rousseldenis commented on product_supplierinfo_revision/wizards/supplierinfo_duplicate_wizard.py
> +            supplierinfo_news |= item.copy(
I suggest to use ids list instead of recordset for performances reasons.

2021-11-11 13:12 UTC, joao-p-marques approved these changes
Code review. LGTM :+1:

2021-11-11 15:05 UTC, rousseldenis approved these changes

2021-11-11 15:37 UTC, pedrobaeza commented
/ocabot merge nobump

2021-11-11 16:08 UTC, merged