[15.0] [MIG] product_cost_security
OCA/product-attribute pull request #964
Opened 2021-12-16 05:10 UTC by celm1990

2021-12-22 07:29 UTC, rousseldenis commented
/ocabot migration product_cost_security

2021-12-22 07:31 UTC, rousseldenis requested changes
Thanks for your contribution

2021-12-22 07:31 UTC, rousseldenis commented on product_cost_security/models/product.py
> +class ProductProduct(models.Model):
Could you split one model per file ?

2021-12-30 02:15 UTC, celm1990 commented
@rousseldenis is OK???

2021-12-30 09:35 UTC, rousseldenis approved these changes
Could you squash your commits ?

2022-01-11 21:49 UTC, celm1990 commented
somebody can help me review this PR?
ping @OCA/oca-members  @OCA/product-maintainers

2022-01-11 22:19 UTC, pedrobaeza approved these changes

2022-01-11 22:19 UTC, pedrobaeza commented
/ocabot merge nobump

2022-01-11 22:24 UTC, merged