[15.0] [MIG] product_dimension
OCA/product-attribute pull request #965
Opened 2021-12-16 05:32 UTC by celm1990

2021-12-17 11:24 UTC, ajaniszewska-dev approved these changes

2021-12-22 07:26 UTC, rousseldenis commented
/ocabot migration product_dimension

2021-12-22 07:29 UTC, rousseldenis requested changes
Thanks for your contribution.

2021-12-22 07:29 UTC, rousseldenis commented on product_dimension/models/product.py
> +    product_length = fields.Float("length")
Could you put fields definition on top ?

2021-12-22 07:29 UTC, rousseldenis commented on product_dimension/models/product.py
> +class ProductTemplate(models.Model):
Could you split one model per file ?

2021-12-22 07:29 UTC, rousseldenis commented on product_dimension/models/product.py
> +    dimensional_uom_id = fields.Many2one(
Same as above

2021-12-22 12:08 UTC, i-vyshnevska commented
pls consider to check discussion in this PR https://github.com/OCA/product-attribute/pull/957 before merging

2021-12-22 13:37 UTC, simahawk requested changes
waiting for https://github.com/OCA/product-attribute/pull/965#issuecomment-999528518 evolution

2021-12-22 14:09 UTC, gurneyalex approved these changes

2022-01-22 04:50 UTC, celm1990 commented
> waiting for #957 evolution

Hi @simahawk the other PR already is merge, but into this module I must be change field type from `Float `to `Integer`???
Is confused for me, because fields into `product.product` are Float(https://github.com/odoo/odoo/blob/15.0/addons/product/models/product.py#L124-L125), only on `stock.package.type `fields are Integer(https://github.com/odoo/odoo/blob/15.0/addons/stock/models/stock_package_type.py#L19-L20) but are models are independent

Thanks for your comments

2022-01-23 16:27 UTC, i-vyshnevska commented
@celm1990 
https://github.com/OCA/product-attribute/pull/957 is about keeping the same type as in origin delivery https://github.com/odoo/odoo/blob/c9bfda40b48b3625765b7d220944938323350d0b/addons/delivery/models/product_packaging.py#L17
AFAIS this model was removed on v15 so I suppose you just need to rebase history and remove product_packaging.py file in the migration step

2022-01-23 17:29 UTC, celm1990 commented
> @celm1990
> #957 is about keeping the same type as in origin delivery https://github.com/odoo/odoo/blob/c9bfda40b48b3625765b7d220944938323350d0b/addons/delivery/models/product_packaging.py#L17
> AFAIS this model was removed on v15 so I suppose you just need to rebase history and remove product_packaging.py file in the migration step

`delivery `inherit `stock.packing.type`(https://github.com/odoo/odoo/blob/15.0/addons/stock/models/stock_package_type.py#L19-L20) instead of  `product.packaging`(https://github.com/odoo/odoo/blob/15.0/addons/product/models/product.py#L752) but both models exist on V15

Sorry but i not see because this module is related or need changes from other module

2022-01-23 19:05 UTC, i-vyshnevska commented
@celm1990 sorry for misleading your PR about "product_dimension" https://github.com/OCA/product-attribute/pull/957 is about "product_packaging_dimension" addon, no direct relation here

2022-01-23 19:10 UTC, i-vyshnevska approved these changes

2022-01-26 12:41 UTC, celm1990 commented
@simahawk can you update your review please

2022-01-27 06:36 UTC, simahawk approved these changes
pls fix pre-commit

2022-01-27 13:04 UTC, celm1990 commented
> pls fix pre-commit

Sorry but I not understand what is error on pre-commit????
![image](https://user-images.githubusercontent.com/7775116/151364200-58e7c8c0-9dac-4cb8-b390-dbb091d8ecd5.png)

2022-02-04 02:28 UTC, celm1990 commented
ping @simahawk  @gurneyalex

2022-02-04 06:17 UTC, simahawk commented
/ocabot merge patch

2022-02-04 06:21 UTC, merged